### PR TITLE
Added some useful feature

### PR DESCRIPTION
**Pull request by kjl98**
Added some useful changes, set suitable margins and added useful hover effects .

### CODE REVIEW

**Comment by kjl98** [comment]
Hello [@mansiruhil13] , I want to say that why did you not merged these changes in your repo?
Is there any mistake in my code? Please let me know something about it.

**Comment by mansiruhil13** [comment]
issue no??

**Comment by mansiruhil13** [comment]
screenshot of output? or recording?

**Comment by mansiruhil13** [comment]
there are conflicts, resolve
Screenshot 2024-10-14 210358

**Comment by kjl98** [comment]
> screenshot of output? or recording?

https://github.com/user-attachments/assets/23d66f50-bb26-423a-92f1-0b087f73c378

**Comment by mansiruhil13** [comment]
sorry but i can't merged. as footer is already there and different from this. you can work on other issue/ feature.

**Pull request closed without merging**
