### PR TITLE
Resolved #374

### LINKED ISSUE #374: [Bug]: Missing Hover effect in Sign-up & subscribe button
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

 **Hover effect** is missing in Sign-up and subscribe button . We should add the feature for the better User experience.

### Add Screenshots

_No response_

### What browsers are you seeing the problem on?

_No response_

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

### PR DESCRIPTION
**Pull request by Deepak0yadav**
Added Hover effect on subscribe & Sign-up buttons

Uploading Screen Recording 2024-10-09 005910.mp4…

### CODE REVIEW

**Comment by mansiruhil13** [comment]
resolve conflicts. and second thing can you share screenshot

**Comment by mansiruhil13** [comment]
and there is password strength add on signup page so can you make changes into the code acc to that

**Comment by Deepak0yadav** [comment]
> resolve conflicts. and second thing can you share screenshot

Can u pls assist me how should how I resolve them

**Comment by Deepak0yadav** [comment]
Preview it 


https://github.com/user-attachments/assets/b333ec7d-7801-48a6-965d-bd0752fffe72

**Comment by Deepak0yadav** [comment]
@mansiruhil13 ,Please preview it and merge it

**Comment by Deepak0yadav** [comment]
> and there is password strength add on signup page so can you make changes into the code acc to that

I am not able to understand can u make it more clear

**Comment by Deepak0yadav** [comment]
@mansiruhil13 , I have resolved the conflicts

**Comment by Deepak0yadav** [comment]
Please merge it

**Comment by mansiruhil13** [comment]
why there are two newsletters??
it should look like this:
Screenshot 2024-10-11 180203

**Comment by Deepak0yadav** [comment]
@mansiruhil13 ok I will fix it

**Comment by Deepak0yadav** [comment]
### Added Hover effects to the buttons  
### Fixed some bugs also

https://github.com/user-attachments/assets/aef92929-848f-47af-8c0c-a26c8839a8ac

@mansiruhil13 ,Please now preview it and merge it

**Comment by Deepak0yadav** [comment]
There were lot of commit issues which I faced and it took my almost 1 hour to look and resolve them. So please assign it under the **label** **level2**

**Pull request closed without merging**
