### PR TITLE
issue#176-fixed

### PR DESCRIPTION
**Pull request by uzefaqureshi06**

### CODE REVIEW

**Comment by mansiruhil13** [comment]
can you share screenshot or recording??

**Comment by mansiruhil13** [comment]
> _ No description provided. _

screenshot???

**Comment by mansiruhil13** [comment]
> > _ No description provided. _
> 
> screenshot???

..

**Comment by uzefaqureshi06** [comment]
Capture  @mansiruhil13 this is the screenshot can you please review it and merge it

**Comment by uzefaqureshi06** [comment]
@mansiruhil13 and can you tell me how would liked it ?

**Comment by mansiruhil13** [comment]
but page have done some changes already, if i merge this, there may be vast change in the whole page? can you check you changes and made for the new homepage? and generate a new pr

**Comment by mansiruhil13** [comment]
Screenshot 2024-10-07 205613

**Comment by mansiruhil13** [comment]
also there was faq section added so there might be changes if i will merge this

**Comment by uzefaqureshi06** [comment]
@mansiruhil13 so can you tell me what I can do for this

**Comment by mansiruhil13** [comment]
> @mansiruhil13 so can you tell me what I can do for this

you can make changes respective the code and create pr again with current changes

**Pull request closed without merging**
