### PR TITLE
This PR is related to the issue no. #$453.Files terms.html has been added

### PR DESCRIPTION
**Pull request by Priyank00007**
image
I have added the file of Terms of Services and also updated the UI of Terms of Services page.

### CODE REVIEW

**Comment by Priyank00007** [comment]
> add issue no. properly , e.g. : issue #453

okay mam so do I need to close the issue or is it closed?

**Comment by mansiruhil13** [comment]
> > add issue no. properly , e.g. : issue #453
> 
> okay mam so do I need to close the issue or is it closed?

closed

**Comment by Priyank00007** [comment]
mam do i create a new issue for site map?

**Comment by mansiruhil13** [comment]
yes

**Comment by Priyank00007** [comment]
> yes

ok mam

**Pull request merged**
