### PR TITLE
added language translator 

### PR DESCRIPTION
**Pull request by ananyag309**
#658 

image

image

image

### CODE REVIEW

**Comment by ananyag309** [comment]
@mansiruhil13 please review and merge it

**Comment by mansiruhil13** [comment]
there are conflicts, resolve and there is a change for toggle key for dark theme. can you do changes acc to that?

**Comment by ananyag309** [comment]
@mansiruhil13 ma'am i have resolved the conflicts please check

**Comment by mansiruhil13** [comment]
still conflicts 
Screenshot 2024-10-14 213739

**Comment by ananyag309** [comment]
image
@mansiruhil13 done

**Pull request merged**
