### PR TITLE
Add toggle to dark mode button

### PR DESCRIPTION
**Pull request by Ishika-Gupta06**
https://github.com/user-attachments/assets/f05c96a0-d21a-47b4-88f9-ffa319407876

Dark Mode Toggle Button: A button with an icon 🌙 is added next to the login link. When clicked, it toggles the dark mode.

Dark Mode Styles: CSS styles are defined for dark mode, which changes the background and text colors.

JavaScript Functionality: An event listener is added to the toggle button. When clicked, it toggles the dark-mode class on the body and content div.

### CODE REVIEW

**Comment by mansiruhil13** [comment]
can you make toggle button for dark mode again, its' disable?

**Comment by mansiruhil13** [comment]
> can you make toggle button for dark mode again, its' disable?

not changed

**Comment by Ishika-Gupta06** [comment]
@mansiruhil13 feature added
Screenshot 2024-10-07 221540

**Comment by mansiruhil13** [comment]
> @mansiruhil13 feature added Screenshot 2024-10-07 221540

not shown, due to breakdown of homepage. page was broken.

**Pull request merged**
