### PR TITLE
New Cards Added in features

### PR DESCRIPTION
**Pull request by i-shivii**
Title: [Feature] " New cards added "

Description:
- Added new cards for features page

- tasks #679.

Note:
- please have a look and let me know if any further changes are needed or not .

### CODE REVIEW

**Comment by mansiruhil13** [comment]
and some changes on features. do changes accordingly

**Comment by i-shivii** [comment]
https://github.com/user-attachments/assets/051ba57a-f092-4a92-a5f8-ecd4f8cc4c21

These are the required changes. I have added new animation cards . and if you liked it , then I will do more changes accordingly.

**Comment by i-shivii** [comment]
https://github.com/user-attachments/assets/58edecb4-534b-4e89-b1b3-c352494f989c

these are the required changes .I have added new cards with same color code as before. if you want ,I will make more changes in whole feature section.

**Comment by 4F24L** [comment]
Resolve Conflicts !!

**Comment by i-shivii** [comment]
Could you please clarify which conflicts you are referring to?

**Comment by i-shivii** [comment]
Now , check  I have resolved it.

**Comment by mansiruhil13** [comment]
remove translate? that's extra on navbar

**Pull request merged**
