### PR TITLE
issue #274 solved✨

### PR DESCRIPTION
**Pull request by T-Rahul-prabhu-38**
Screenshot 2024-10-06 at 10 16 45 PM

solved all the problems highlighted in issue #274

### CODE REVIEW

**Comment by T-Rahul-prabhu-38** [comment]
@mansiruhil13 can you confirm this.

**Comment by T-Rahul-prabhu-38** [comment]
can you add the levels as well, thank you!

**Comment by mansiruhil13** [comment]
Screenshot 2024-10-06 222213
there is bug

**Comment by T-Rahul-prabhu-38** [comment]
oh ill check that.

**Comment by mansiruhil13** [comment]
you have to create another pr, for all changes you make

**Comment by T-Rahul-prabhu-38** [comment]
sure

**Comment by T-Rahul-prabhu-38** [comment]
the home page has some problems too , ill create a new issue for that aswell

**Comment by mansiruhil13** [comment]
yes

**Comment by mansiruhil13** [comment]
you can close this pr

**Pull request merged**
