### PR TITLE
home-page unwanted scroll fixed on navbar

### PR DESCRIPTION
**Pull request by kunal649**
As i was only allowed to work on home page, i fixed that unwanted scroll in buttons - on home page

https://github.com/user-attachments/assets/42511d0a-5ba2-4c97-8fa3-e14ebae98f4c

### CODE REVIEW

**Comment by mansiruhil13** [comment]
you have to create issue first

**Comment by mansiruhil13** [comment]
in navbar nearby and feedback section also there like home contact. and second, navbar section already assigned.

**Comment by kunal649** [comment]
BUT I ALREADY CREATED .. CHECK ISSUE 448 & CLOSE THAT

**Comment by kunal649** [comment]
i already created the issue 3 days ago ( ID-448) and here it is solved ( as per restrictions , im only allowed to make any change on home page rest are assigned to others, so close the PR ) @mansiruhil13

**Comment by 4F24L** [comment]
On the homepage, no issue is present like that !!

**Pull request closed without merging**
