### PR TITLE
[Fix] : Home Page UI FIX #604

### LINKED ISSUE #604: [Bug]: Home Page UI FIX
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When I land on the homepage, the responsiveness doesn't work properly on small devices, and on larger devices, some navbar buttons overflow from the navbar.

### Add Screenshots

Screenshot (8)
Screenshot (9)

### What browsers are you seeing the problem on?

_No response_

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

### PR DESCRIPTION
**Pull request by saurabh-dev-vns**
Issue : #604

UI changes have been made for the homepage.

Screenshot (12)
Screenshot (13)
Screenshot (14)

### CODE REVIEW

**Comment by saurabh-dev-vns** [comment]
@4F24L, @mansiruhil13, please go ahead and merge this PR.

If you want the other pages to be responsive as well, feel free to assign them to me again.

**Comment by mansiruhil13** [comment]
resolve conflicts

**Comment by saurabh-dev-vns** [comment]
@mansiruhil13, Conflicts are resolved. Now you can merge this PR.

**Comment by saurabh-dev-vns** [comment]
@mansiruhil13, Conflicts are resolved. Now you can merge this PR.

**Comment by mansiruhil13** [comment]
there are conflicts, resolve. and toggle feature for dark theme added recently so do changes acc to that

**Comment by mansiruhil13** [comment]
there are few changes done already. could you make changes into your code accordingly??

**Comment by saurabh-dev-vns** [comment]
@mansiruhil13, please merge the branch; otherwise, an error will occur again and put me in a bad mood.

**Comment by saurabh-dev-vns** [comment]
Thankyou

**Pull request merged**
