### PR TITLE
Features added 

### PR DESCRIPTION
**Pull request by Ishika-Gupta06**
@mansiruhil13 
_Features:_
>Dark Mode feature added for better UI
>Scroll to Top feature
>Better footer For web page

### CODE REVIEW

**Comment by mansiruhil13** [comment]
there are conflicts in pr, resolve conflicts

**Comment by Ishika-Gupta06** [comment]
@mansiruhil13  conflict resolved.

**Comment by mansiruhil13** [comment]
after merged, issues arises: 
Screenshot 2024-10-08 230037
also toggle button for dark mode not working

**Comment by mansiruhil13** [comment]
also footer have been broken on home
Screenshot 2024-10-08 230212

**Pull request merged**
