### PR TITLE
Change Navbar(made in same for all pages)

### PR DESCRIPTION
**Pull request by Arisha2902**
Change the background color of navbar,
change font-color, border and hover effect to make navbar look same on all  pages.

Made  Darkmode icon on features page.

Brought all buttons of navbar in same allignment

### CODE REVIEW

**Comment by mansiruhil13** [comment]
there are conflicts, resolve

**Comment by mansiruhil13** [comment]
landing page is added yesterday. so can you made into your code accordingly

**Comment by Arisha2902** [comment]
> there are conflicts, resolve

I  do am resolving it right now,just give me some time.
i will resolve it by today

**Comment by Arisha2902** [comment]
> there are conflicts, resolve

Actualy I have tried to solve conflict and many changes in it as well ,but now the conflict is only "indentation error".
As you can see ,in the given ss the error in "team.html" is only lines
WhatsApp Image 2024-10-16 at 9 53 30 PM

And the erorr in "features.html" is just in "indentation " only 
WhatsApp Image 2024-10-16 at 9 53 30 PM (1)



The site is completely is same and constant for all pages, as commanded to do.Only problem lies in these Indentation.

Uploading final2.mp4…



I have been trying to solve these error from past few hours but couldn't do ,please see to this issue and tell to me do required.

**Comment by mansiruhil13** [comment]
screenshot?

**Comment by Arisha2902** [comment]
> screenshot of output

Screenshot (13)
Screenshot (12)
Screenshot (11)
Screenshot (9)



this is the final output.All pages have same navbar.

I can't make changes in landing page right now bcuz my sessional is going but after 28 I can make changes in landing page as well.

And if you agree so I can make the navbar responsive as well (if you will allow so I will raise that issue as well),  but I can do all this after 28 only.

Sorry for inconvience but I can do after 28 all the things.

**Comment by Arisha2902** [comment]
> yes there are conflicts. can you resolve them

I will try to resolve them but I can do after 28 but sure It will be done within 2 days.
If you allow so I will do that after28

**Comment by Arisha2902** [comment]
Actually two people are working on same page , so that's why there are conflict .

You should accept my merge request first then other people change will also be accept .

I have Change navbar alignment and background color and other people are making scroll bar on the same page so that's why there is conflict.
My changes are right accept my request then let other change the same page .In this way both people  changes will be accepted easily.

**Comment by Arisha2902** [comment]
I have done resolve the conflict , plz do accept it before anyone else make changes in same page

**Comment by mansiruhil13** [comment]
there are conflicts.

**Comment by mansiruhil13** [comment]
and navbar is changes on all pages. only feedback, you can create changes.

**Comment by Arisha2902** [comment]
> there are conflicts.

Ma'am the conflict are only bcuz other people are also making changes on same pages.I have already resolved the conflict 4 times , bcuz other people also make change at same time .

If I resolve conflict now then until you come online there will be new conflict so plz msg when you come online so I will resolve conflict at that time, and u will be able to accept my pull request at that time only .


Bcuz there is no use to resolve conflict now, until and unless you accept my pulls request at same time.

**Comment by Arisha2902** [comment]
My navbar was also good but if you like that one , then plz do close this issue 

Except for the fact that you assigned this issue to 2 different person at same time  and choosed which one look better and let other make changes , but not accpet we d that

**Pull request closed without merging**
