### PR TITLE
change in  footer section

### PR DESCRIPTION
**Pull request by ganjivamshiii**
i think i solved issue. Quick links part
Screenshot 2024-10-10 190239

### CODE REVIEW

**Comment by mansiruhil13** [comment]
what's the issue? can you elaborate?

**Comment by ganjivamshiii** [comment]
image
"In the footer quick links, links are missing in mobile view. I believe I have fixed the issue, check once"

**Comment by mansiruhil13** [comment]
issue no??

**Comment by ganjivamshiii** [comment]
issue no: #514

**Pull request merged**
