### PR TITLE
Resolved: Favicon missing on subpage Pages and bugs in README file

### LINKED ISSUE #969: [Bug]: Favicon missing in Home and Nearby Page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The favicon of the Website is missing in two web pages: **Home page** and the **Nearby page**:

### Add Screenshots

The favicon of the Website is missing in two webpages:
image

It is missing in the **Home page** and the **Nearby page**:
image

### What browsers are you seeing the problem on?

_No response_

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

### PR DESCRIPTION
**Pull request by rajdeepchakraborty-rc**
### Missing Favicon on Subpages:
Added the missing Favicons to the Home and Nearby pages and also to the new Feedback page(recently added).

### Readme Program Banners Updation:
I have updated the banners to fit better in the README file. I have updated the GSSoC banner to GSSoC Extended Program banner and also adjusted the orientation of the Hacktoberfest Banner(a banner is usually landscape and should be more on length that on breadth)

### Readme file Team section:

Due to changing your profile picture again the Team Section was broken. I have fixed and adjusted the Team section back to the normal size:

- Fixes #969 

### Missing Favicon on Subpages:

- Before:
It is missing in the **Home page** and the **Nearby page**:
image

- After:
Home:
image
Nearby:
image
Feedback:
image

### Readme Program Banners Updation:

- Before:
image

- After:
image

### Readme file Team section:

- Before:

image

- After:

image

## Type of Change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] Documentation update

## Checklist

- [X] I have read the contributing document.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have added necessary tests to ensure my changes are effective.
- [X] New and existing unit tests pass locally with my changes.
- [X] Any dependent changes have been merged and published in downstream modules.

## Additional Information

---
Please review the PR and assign it to me with the necessary labels.

### CODE REVIEW

**Comment by mansiruhil13** [comment]
issue no??

**Comment by rajdeepchakraborty-rc** [comment]
> issue no??

It is present in the description of the PR. I have followed the given template

**Review by MastanSayyad — COMMENTED** [review]
Reducing levels to 1 @rajdeepchakraborty-rc 

- empty spaces 
- code formatting 
- added comments 
- few minor changes. 

@mansiruhil13 if you're on discord or LinkedIn kindly DM me or any other Program Manager 


(dont worry you seem beginner as a PA, i can see you never review the code, so just want to clarify some guidlines and proper labelling of points)

**Comment by rajdeepchakraborty-rc** [comment]
@MastanSayyad Ok. I trust your judgment. I want to express my sincere apologies for any missteps on my end, should there have been any.

**Pull request merged**
