### PR TITLE
Hover animation added on all pages with responsive icons.

### PR DESCRIPTION
**Pull request by rajdeepchakraborty-rc**
Issue #333 [SOLVED] 

## Updated the Newsletter

https://github.com/user-attachments/assets/353efba4-7be3-4d77-8349-ad4147456310

Since I have updated most of the things, thus I am only adding the video of the work done.

### CODE REVIEW

**Comment by rajdeepchakraborty-rc** [comment]
Please add the necessary labels and assign the PR to me: 

- level3
- gssoc-ext
- hacktoberfest-accepted

**Comment by rajdeepchakraborty-rc** [comment]
Also wanted to let you know about something:
Incase you find any changes required while reviewing a PR, you can ask for a change in it. You don't need to close the PR necessarily.

**Comment by rajdeepchakraborty-rc** [comment]
@mansiruhil13, Please review the PR. I wanted to remind you about it.

**Comment by mansiruhil13** [comment]
Screenshot 2024-10-08 232232
there are conflicts, resolve

**Comment by rajdeepchakraborty-rc** [comment]
Seems that you have merged some code again. Let me check

**Comment by rajdeepchakraborty-rc** [comment]
The site is broken!
image
image

**Comment by mansiruhil13** [comment]
> The site is broken! image image

yes but assigned recently

**Comment by rajdeepchakraborty-rc** [comment]
Somebody has messed up with my code pretty bad

image

I would love to know who this person is who thought of adding a dropdown on social icons.

**Comment by mansiruhil13** [comment]
Screenshot 2024-10-09 001059
resolve conflicts

**Comment by rajdeepchakraborty-rc** [comment]
@mansiruhil13 Somehow after lot of merge conflicts later... I have resolved it.

**Comment by rajdeepchakraborty-rc** [comment]
I was uploading the change. That is why you were seeing the conflicts. You had again merged some code a while back. had to resolve that too.

**Comment by rajdeepchakraborty-rc** [comment]
I have to admit that working on this issue was really something. I can set this issue a record of merge conflicts. I have lost count at this point of how many times I have resolved the code.

**Comment by rajdeepchakraborty-rc** [comment]
Not again!

**Comment by mansiruhil13** [comment]
> I have to admit that working on this issue was really something. I can set this issue a record of merge conflicts. I have lost count at this point of how many times I have resolved the code.

yes, there are many issues created. 😅

**Comment by mansiruhil13** [comment]
> Not again!

resolve conflicts

**Comment by rajdeepchakraborty-rc** [comment]
> > I have to admit that working on this issue was really something. I can set this issue a record of merge conflicts. I have lost count at this point of how many times I have resolved the code.
> 
> yes, there are many issues created. 😅

No worries. Even you are having a hard timing manage the code. Ok ma'am, as you wish. I shall dive into the code conflict again.

**Comment by rajdeepchakraborty-rc** [comment]
@mansiruhil13 I hereby present myself to you once again

**Comment by rajdeepchakraborty-rc** [comment]
Thanks for reviewing! Please assign the PR to me.

**Comment by rajdeepchakraborty-rc** [comment]
Also close the issue #333

**Comment by rajdeepchakraborty-rc** [comment]
@mansiruhil13 Thanks for assigning the PR. Sorry for irritating you so much during this PR review😅
I have some other issues pending. Once I am done working on them, I will get back to committing more to this project. Hope you have a great day ahead!

**Pull request merged**
