### PR TITLE
#15  added README file  for local running of the application 

### PR DESCRIPTION
**Pull request by nagajaideep**
added the necessary changes from the resource given by the mentor

### CODE REVIEW

**Review by yashksaini-coder — APPROVED** [review]
Hey @nagajaideep just checking to ensure your changes don't cause any conflict to the deployed static site

Overall your changes are really good, necessary and does not cause any conflicts with mine.

**Comment by nagajaideep** [comment]
hey @yashksaini-coder yeah there was an small issue when merging (it is showing build error) not sure how to fix that 
image

**Comment by yashksaini-coder** [comment]
@nagajaideep I created a build-deploy workflow script. as there was no github actions generally present at that time. So this script naturally build the site & deploy them. 

However after merging the PR, deploy job fails as there is already settings configured on the project to build & publish. That's why deploymeny job doesn't work.

**Comment by yashksaini-coder** [comment]
i can fix the configuration settings if I have access to main repo as collaborator.

**Comment by yashksaini-coder** [comment]
@nagajaideep can you tell me what issue does this PR #16 fixes ?

**Comment by nagajaideep** [comment]
#16 pull req: this have changes in the readme file on how to run the application locally on your system and I've also added the template for pull request 

there are no merge conflicts when when added to my forked repo only deployment issues 

 i have no idea what went wrong if you don't mind can you explain what is the issue exactly about given in the screenshot above

**Comment by mansiruhil13** [comment]
> #16 pull req: this have changes in the readme file on how to run the application locally on your system and I've also added the template for pull request
> 
> there are no merge conflicts when when added to my forked repo only deployment issues
> 
> i have no idea what went wrong if you don't mind can you explain what is the issue exactly about given in the screenshot above

issue is to enhance live location of ambulance on google map

**Comment by yashksaini-coder** [comment]
@mansiruhil13 can you add gssoc & hacktoberfest labels in this PR,

**Pull request merged**
