### PR TITLE
fix: 🐛 Revamp UI & user interface

### LINKED ISSUE #833: [Bug]: The UI & user interface is severly lacking
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I find that the UI and functioning is very poor so I would like to enhance it, mostly the backend code for better chatbot interface & working.

- Update the UI: Add a section to show the file list.
- Modify JavaScript: Capture file information and display it in the chat.
- Chatbot interface: improve the chatting interface and adding javascript to make it more better.

### Add Screenshots

image

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

### PR DESCRIPTION
**Pull request by yashksaini-coder**
## Description

- Fixes #833 

## Screenshots (if applicable)
[Bobble-833.webm](https://github.com/user-attachments/assets/553cfff4-9058-4576-ae1b-f7e31ccbcdd1)

## Type of Change

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

- [X] I have read the contributing document.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have added necessary tests to ensure my changes are effective.
- [X] New and existing unit tests pass locally with my changes.
- [X] Any dependent changes have been merged and published in downstream modules.

## Additional Information

---

### CODE REVIEW

**Comment by yashksaini-coder** [comment]
@mansiruhil13 can you review this PR, and add proper labels to it. 

I recreated the chatbot with response loading animations, and responsive

**Comment by yashksaini-coder** [comment]
@mansiruhil13 can you review this PR and also assign it  to me

**Comment by yashksaini-coder** [comment]
@mansiruhil13 can you review this PR, before merge conflicts arises,  @MastanSayyad can you look into this PR.

**Comment by yashksaini-coder** [comment]
@MastanSayyad can you look into this PR review and let the PA know

**Comment by yashksaini-coder** [comment]
@mansiruhil13 can you revie my PR & add proper labels to it, It's been sometime this PR is opened for quite a long time

**Comment by mansiruhil13** [comment]
but chatbot already there with voice adding button.

**Comment by yashksaini-coder** [comment]
> but chatbot already there with voice adding button. 

@mansiruhil13 thank you for responding 

No it's for proper responsive and interface plus added a typing animation which is shown during the process of generating responses

I shared my approach to you before You were active on the repo project, after that you assigned it to me.

Just give it level 1 as it is only js backend req res enhancement with CSS loading effect on response generation 

Also happy Diwali 🎆

**Pull request closed without merging**
