### PR TITLE
Fixed Login Page and some minor issues #158

### PR DESCRIPTION
**Pull request by devarsheecodess**
https://github.com/user-attachments/assets/9450cd8b-1777-44ed-882d-7908fec6e4a7

Changes made:
1. Removed header from login page
2. Replaced Hospital Management System with AmbuFlow in the entire project

### CODE REVIEW

**Review by mansiruhil13 — APPROVED** [review]

**Comment by mansiruhil13** [comment]
amazing, but i saw that when we go home to features to team to contact tab everything works fine .. but go to contact first then home it shows "page not found"
Screenshot 2024-10-05 204332

**Comment by devarsheecodess** [comment]
The person who was assigned to make the landing page had created a seperate file named as home.html and the code was same as index.html. Due to this, i was getting a merge conflict so i had deleted the home.html file. I will fix this now

**Comment by mansiruhil13** [comment]
> The person who was assigned to make the landing page had created a seperate file named as home.html and the code was same as index.html. Due to this, i was getting a merge conflict so i had deleted the home.html file. I will fix this now

ok

**Comment by mansiruhil13** [comment]
> The person who was assigned to make the landing page had created a seperate file named as home.html and the code was same as index.html. Due to this, i was getting a merge conflict so i had deleted the home.html file. I will fix this now

but the issue was assigned already, you can find another issue if you want

**Comment by devarsheecodess** [comment]
> > The person who was assigned to make the landing page had created a seperate file named as home.html and the code was same as index.html. Due to this, i was getting a merge conflict so i had deleted the home.html file. I will fix this now
> 
> but the issue was assigned already, you can find another issue if you want

I had fixed it btw, just one line was to be changed 

https://github.com/user-attachments/assets/ae60a7f9-e318-4668-80c5-957b49afe11b

**Comment by mansiruhil13** [comment]
okay

**Comment by devarsheecodess** [comment]
should i commit these changes?

**Comment by mansiruhil13** [comment]
yes

**Comment by devarsheecodess** [comment]
@mansiruhil13 plz add gssoc-ext label to this PR too

**Comment by devarsheecodess** [comment]
Thank you so much !

**Pull request merged**
