### PR TITLE
Translation of website

### PR DESCRIPTION
**Pull request by CodeMosaic7**
Solved issue id: Website Translation using Google Translate API #231

### CODE REVIEW

**Comment by mansiruhil13** [comment]
there are conflicts resolve

**Comment by mansiruhil13** [comment]
and attach screenshot or recording to review?

**Comment by CodeMosaic7** [comment]
home page
image

features page
image

contact page
image

team page
image

**Comment by mansiruhil13** [comment]
Screenshot 2024-10-14 214309
still conflicts.

**Comment by mansiruhil13** [comment]
and already done this. with chatbot and toggle key for dark theme. 
Screenshot 2024-10-14 214337
if you can improve ui, you can make changes. otherwise no need.

**Comment by CodeMosaic7** [comment]
I would like to try.

**Comment by CodeMosaic7** [comment]
Does this mean the pull request is accepted? and I can work with UI.

**Comment by mansiruhil13** [comment]
> Does this mean the pull request is accepted? and I can work with UI.

actually translation done already. sorry but i can't merge this one. you can work on other issues. i am really sorry

**Pull request closed without merging**
