### PR TITLE
Home page UI change

### LINKED ISSUE #630: [Feature Request]: Home page UI change
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to make changes to the UI of the home page.
From This: 
Screenshot (398)
To this:
Screenshot (399)

### Use Case

This will enhance the overall user experience and make the project more appealing 

### Benefits

_No response_

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

### PR DESCRIPTION
**Pull request by KhawajaFashi**
### The new UI change that includes animation will increase the overall user experience and it will be appealing to the user
fixes #630  
#### Before: 

Screenshot (411)

#### After UI change:

Screenshot (412)

### CODE REVIEW

**Comment by mansiruhil13** [comment]
and there are conflicts also. 
Screenshot 2024-10-14 213834

**Comment by KhawajaFashi** [comment]
> actually there are some changes as there is dark mode theme also added. can you make changes acc to that?

Yes mam I considered that issue but the dark mode was not working so I skipped it for now if you want I can add the button then the functionality can be added later.

**Comment by KhawajaFashi** [comment]
I will look into it.
> and there are conflicts also. 
> Screenshot 2024-10-14 213834
>

**Comment by mansiruhil13** [comment]
> > actually there are some changes as there is dark mode theme also added. can you make changes acc to that?
> 
> Yes mam I considered that issue but the dark mode was not working so I skipped it for now if you want I can add the button then the functionality can be added later.

its' added and translator also. so do changes accordingly. after that i can merged this.

**Comment by mansiruhil13** [comment]
> > > actually there are some changes as there is dark mode theme also added. can you make changes acc to that?
> > 
> > 
> > Yes mam I considered that issue but the dark mode was not working so I skipped it for now if you want I can add the button then the functionality can be added later.
> 
> its' added and translator also. so do changes accordingly. after that i can merged this.

there is assigned for translator. so do changes acc to that, after that. please. so that this pr don't make any blunder.

**Comment by KhawajaFashi** [comment]
> > > > actually there are some changes as there is dark mode theme also added. can you make changes acc to that?
> > > 
> > > 
> > > Yes mam I considered that issue but the dark mode was not working so I skipped it for now if you want I can add the button then the functionality can be added later.
> > 
> > its' added and translator also. so do changes accordingly. after that i can merged this.
> 
> there is assigned for translator. so do changes acc to that, after that. please. so that this pr don't make any blunder.

Yes mam I am looking into it solving the conflicts.

**Comment by KhawajaFashi** [comment]
Sorry for the inconvenience earlier now everything is working as it should
https://github.com/user-attachments/assets/f10a345d-09f2-46a5-a3cb-542135dec059

**Comment by mansiruhil13** [comment]
there are conflicts, resolve
Screenshot 2024-10-15 150206

**Comment by mansiruhil13** [comment]
you made changes only on home? and features, contact, nearby, etc..

**Comment by KhawajaFashi** [comment]
@mansiruhil13  i have resolved all the conflicts you can merge it now.
Screenshot (416)

**Comment by KhawajaFashi** [comment]
> you made changes only on home? and features, contact, nearby, etc..

Yes mam I am to synchronize this navbar design across all pages I just wanted to see if you liked the design then I can create the issue to synchronize on all pages

**Comment by mansiruhil13** [comment]
Screenshot 2024-10-15 174716

**Comment by KhawajaFashi** [comment]
@mansiruhil13  I think You merged some code which raised the conflict because I have made changes to almost all of the page so it is sure to have a conflict if you merge some code.

**Comment by mansiruhil13** [comment]
you have to change on all pages. because now nav bar is different on all pages

**Pull request merged**
