### PR TITLE
footer of this website not completely responsive and Aline content accurately 

### PR DESCRIPTION
**Pull request by Ankul8471**
#517
L2
L3
L4

### CODE REVIEW

**Comment by Ankul8471** [comment]
@mansiruhil13  hello Mam's please review my contribution and merge it

**Comment by Ankul8471** [comment]
@mansiruhil13 Hello Mam's please review my contribution and merge it

**Comment by mansiruhil13** [comment]
there are conflicts, resolve. and few changes done recently. so please do changes accordingly

**Comment by Ankul8471** [comment]
hello mam's i solve this issue, please merge it

**Comment by Ankul8471** [comment]
@mansiruhil13 Hello mam I solved this issue, please merge it and give level 2 as you gave previously...

**Comment by Ankul8471** [comment]
@mansiruhil13 Hello  I solved this issue, please merge it and give level 2 as you gave previously...

**Comment by mansiruhil13** [comment]
> @mansiruhil13 Hello I solved this issue, please merge it and give level 2 as you gave previously...

recording??

**Comment by mansiruhil13** [comment]
there are conflicts, resolve.

**Pull request closed without merging**
