### PR TITLE
[FIX] Landing page fixed and links are working

### LINKED ISSUE #82: [Bug]: issues
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

in 1st screenshot, header : home ,contact us and about not working
in 2nd: home, features, team, contact not working

### Add Screenshots

Screenshot 2024-10-03 160812
Screenshot 2024-10-03 160835

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

### PR DESCRIPTION
**Pull request by 4F24L**
## Landing page fixed and Links are checked 
- Fixes #82 

image

### CODE REVIEW

**Comment by devarsheecodess** [comment]
You were not assigned the issue so how did you raise a PR now? @4F24L you are not the project admin and you have no right to close my pull request and raise yours!

**Comment by 4F24L** [comment]
Check the issue number. #82

For that this PR is being made.

**Comment by 4F24L** [comment]
Don't compete with each other.

Make contributions in a friendly environment. Every issue should be assigned before the contribution.

**Comment by 4F24L** [comment]
The PR was labelled and merged by admin. Can you keep it as was?

**Pull request merged**
