### PR TITLE
Updated footer and back-to-top button on feature, contact, and team pages

### PR DESCRIPTION
**Pull request by rookieanvesh**
- Adjusted copyright tag in footer
- Align back-to-top button with chatbot button
- Make back-to-top button circular for UI consistency
- Enable page-top access from any location on these pages

Previous features, team and contact pages

Screenshot 2024-10-17 at 4 18 29 AM
Screenshot 2024-10-17 at 4 18 40 AM
Screenshot 2024-10-17 at 4 18 49 AM

New Updated features, team and contact page
Screenshot 2024-10-17 at 4 20 49 AM
Screenshot 2024-10-17 at 4 21 05 AM
Screenshot 2024-10-17 at 4 21 18 AM

### CODE REVIEW

**Comment by rookieanvesh** [comment]
@mansiruhil13 could you please label this under the hacktoberfest2024 and hacktoberfest2024-accepted?

**Comment by mansiruhil13** [comment]
there are conflicts, resolve

**Comment by mansiruhil13** [comment]
and footer has some changes recently. can you check your code again?

**Comment by mansiruhil13** [comment]
and issue no?

**Pull request closed without merging**
