### PR TITLE
[FIX] Fixes Issue #1039 and other bugs

### PR DESCRIPTION
**Pull request by OmAmar106**
Fixes Issue #1039 , removed the bug from the login/signup page , updated the sitemap page and removed a few more bugs were it would show that feedback page is not available.

The Issue fixed can also be veiwed in the attached video.

Files Changed : contact.html , features.html , Feedback.html , nearby.html , sitemap.html , team.html , up.html

https://github.com/user-attachments/assets/1dd20707-c679-4466-a702-61f833cb7a5c

### CODE REVIEW

**Comment by OmAmar106** [comment]
@mansiruhil13 could you please review this and add the gssoc and hacktober tag

**Review by kunal649 — COMMENTED** [review]
see there are duplicate id's ,div's also seems like some script tags are not working. but yeah u tried it nice

**Comment by mansiruhil13** [comment]
> @mansiruhil13 could you please review this and add the gssoc and hacktober tag

there are conflicts in sitemap.html

**Comment by OmAmar106** [comment]
@mansiruhil13 Removed the conflicts.

**Comment by mansiruhil13** [comment]
no changes done after merged??

**Comment by OmAmar106** [comment]
> no changes done after merged??

Nope , last commit I did was 3 days ago after that did not change anything

**Pull request merged**
