### PR TITLE
Fixed the ISSUE #597

### LINKED ISSUE #597: [Feature Request]:  Want to add a star rating based review system.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The website should have been a 5 star rating and a comment based review system. just like the attached video.  

which content 5 stars based rating with cool animation along with a textarea where user give there review. 

Further you can add the backend functionality to display the review.

### Use Case

This looks more authentic.

### Benefits

It should be look like this --> 

https://github.com/user-attachments/assets/e1eb5d63-c210-4dbe-b0f1-ba5f7b42707c

**NOTE**
please add the *hacktoberfest-accepted* label if you assign it to me.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

### PR DESCRIPTION
**Pull request by Suvadip-sana**
---
name: Pull_request_TEMPLATE.yml
about: use this template for creation of pull requests
title: Initially i raised the issue to add the star based rating system but some one may be fix this. So now as I said i add the animation model on stars that looks cool. and also i fixed the UI of this form for both form and the greetings message. As you seen in the recording.
labels: `gssoc-ext, hacktoberfest, hacktoberfest-accepted, level2`  as seen on the ISSUE #597 

---
name: Pull Request Template

## Description

- Fixes #597 

## Screenshots (if applicable)

https://github.com/user-attachments/assets/943219fd-9321-4141-a8ac-a71a1f963639

## Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

- [x] I have read the contributing document.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have added necessary tests to ensure my changes are effective.
- [x] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published in downstream modules.

## Additional Information

---

@mansiruhil13   Please marge this PR. And please add all the labels that are in ISSUE #597

### CODE REVIEW

**Comment by Suvadip-sana** [comment]
@mansiruhil13 please merged this

**Comment by Suvadip-sana** [comment]
@mansiruhil13 Please marge this.

**Comment by Suvadip-sana** [comment]
@mansiruhil13 Marge this

**Comment by mansiruhil13** [comment]
there are conflicts. resolve please

**Comment by Suvadip-sana** [comment]
@mansiruhil13 Solved!

please marge it ASAP.

**Comment by Suvadip-sana** [comment]
@mansiruhil13  Marge it. It's been 3days pending

**Pull request closed without merging**
