### PR TITLE
ADDED THE TRANSLATOR

### PR DESCRIPTION
**Pull request by HS202022**
ADDED THE TRANSLATOR TO EVERY PAGE 
ISSUE  #710
PLEASE GIVE LEVEL 2

https://github.com/user-attachments/assets/3aac05e5-9ce1-44c8-9f8b-8ad7cecda6e1

### CODE REVIEW

**Comment by mansiruhil13** [comment]
sorry but i can't merge this. as its' done already.

**Comment by mansiruhil13** [comment]
but translator already there?

**Comment by HS202022** [comment]
also the previous one doesnt have good ui  
Screenshot 2024-10-14 220928


> can you check again?



> but translator already there?

**Comment by mansiruhil13** [comment]
and toggle key for dark theme??

**Comment by HS202022** [comment]
> and toggle key for dark theme??

ok doing it

**Comment by mansiruhil13** [comment]
and on feedback there are few changes done. can you made changes acc to new one

**Comment by mansiruhil13** [comment]
and homepage also already

**Comment by HS202022** [comment]
> and homepage also already, you have to do changes acc to new one

ok then im doing it again then

**Comment by HS202022** [comment]
https://github.com/user-attachments/assets/e8763b11-686f-4c71-822c-5ee9a5082807

SOMEONE DID THIS BECAUSE IT WASNT THERE FEW MINS BACK

**Comment by HS202022** [comment]
> Untitled.video.-.Made.with.Clipchamp.35.mp4 
> SOMEONE DID THIS BECAUSE IT WASNT THERE FEW MINS BACK

I CAN MAKE IT GOOD I WILL NEED SOMETIME

**Comment by HS202022** [comment]
image
SEE THE CHANGES THAT WERE MADE

**Comment by mansiruhil13** [comment]
> image SEE THE CHANGES THAT WERE MADE THEY JUST MESSED UP IM RESOLLVING IT

there is a blunder created on all the pages by a single issue

**Comment by HS202022** [comment]
> > image SEE THE CHANGES THAT WERE MADE THEY JUST MESSED UP IM RESOLLVING IT
> 
> there is a blunder created on all the pages by a single issue

im resolving it give me some time

**Comment by mansiruhil13** [comment]
can i merge this pr? or any conflicts present?

**Comment by HS202022** [comment]
you can merge this pr only the dark color for the dark mode is not present for the button everything else is fine

**Comment by HS202022** [comment]
> > you can merge this pr only the dark color for the dark mode is not present for the button everything else is fine
> 
> chatbot ?

everything is fine

**Comment by HS202022** [comment]
https://github.com/user-attachments/assets/5dd48ac9-8bbe-4265-a231-9cae3c68e0e2

**Comment by HS202022** [comment]
if possible please give me level 3 cause i figured out so many issue

**Comment by mansiruhil13** [comment]
why there are two translator??

**Comment by HS202022** [comment]
> why there are two translator??

you merged that one first

**Comment by HS202022** [comment]
i can fix all these let me raise 1 issue i will fix all these by 12

**Comment by mansiruhil13** [comment]
> i can fix all these let me raise 1 issue i will fix all these by 12

but some of them assigned recently

**Comment by HS202022** [comment]
> > i can fix all these let me raise 1 issue i will fix all these by 12
> 
> but some of them assigned recently

wait until i send pull request then merge theirs

**Comment by mansiruhil13** [comment]
> > > > i can fix all these let me raise 1 issue i will fix all these by 12
> > > 
> > > 
> > > but some of them assigned recently
> > 
> > 
> > wait until i send pull request then merge theirs
> 
> wait for me till 12 10 if possible

but assigned already

**Pull request merged**
