### PR TITLE
Feedback-form

### PR DESCRIPTION
**Pull request by Bhoomidhanu12**
The Feedback Form is a user-friendly interface designed to collect general inquiries, feedback, and complaints from patients and visitors of the hospital. It consists of essential fields, including the user's name, email address, phone number, feedback type (general inquiry, feedback, or complaint), and a message box for detailed input.

### CODE REVIEW

**Comment by Bhoomidhanu12** [comment]
@mansiruhil13 kindly review my pull request and workflow

**Comment by mansiruhil13** [comment]
screenshot??

**Comment by mansiruhil13** [comment]
issue no??

**Comment by Bhoomidhanu12** [comment]
> issue no??

I raised my suggestion ,not the issue
Screenshot (312)

**Comment by mansiruhil13** [comment]
you have to create issue first.

**Pull request closed without merging**
