### PR TITLE
Fixes : Missing Validation in Newsletter , SignUp Page, and Login Page | Text Justification | BackToTop Scrolling Issue... | Issue #444

### PR DESCRIPTION
**Pull request by Shariq2003**
I have added the follwing :-

1. Email Validation in Newsletter.
2. Toast Alert Notification Newsletter.
3. Smooth Scrolling for BackToTop Button.
4. Login and SignUp page Email Validation.
5. Login and SignUp page Taost Alerts for Success and Failure.
6. I also clean the multiple-written code and the index.html file by removing the styling and adding it to the index.css file for better code understanding for new developers.
7. Fix Dark/Light Mode.

https://github.com/user-attachments/assets/c11df840-18e8-4847-bc6a-c860bd1b8fcf

https://github.com/user-attachments/assets/0a07ba49-22f2-4918-b7c4-64861516c822

Completed #444

### CODE REVIEW

**Comment by Shariq2003** [comment]
@mansiruhil13 please review and merge

**Comment by mansiruhil13** [comment]
and what's the issue no??

**Comment by Shariq2003** [comment]
> and what's the issue no??

I have mentioned 444

**Comment by Shariq2003** [comment]
@mansiruhil13 mam, again the same issues are happening in the main branch
You have merged an another branch that causes the main branch down and also creates problems in other's branch like me 😥,

see the main branch deployment


https://github.com/user-attachments/assets/43e3fffb-d498-4b05-bee8-551f68bc78d8

**Comment by mansiruhil13** [comment]
yes there are few changes done. assigned recently

**Comment by Shariq2003** [comment]
> yes there are few changes done. assigned recently

@mansiruhil13 if u merge the PRs by the Increasing order of issues number than the probability of conflict will be removed.
Maybe 😄

**Comment by mansiruhil13** [comment]
> > yes there are few changes done. assigned recently
> 
> @mansiruhil13 if u merge the PRs by the Increasing order of issues number than the probability of conflict will be removed. Maybe 😄

ok

**Comment by mansiruhil13** [comment]
but as of know already blunder is created

**Comment by Shariq2003** [comment]
> but as of know already blunder is created

No, you can solve them easily

**Comment by Shariq2003** [comment]
> @mansiruhil13 my branch is all set i also shared the video of my branch, u can see that, and if want than set the main branch by my branch as upstream, I mean
> 
> git reset --hard [3ac86a2](https://github.com/mansiruhil13/Bobble-AI/commit/3ac86a2fa07f0e4ff62580e6bfc8eac9dabb7eab)
> 
> or can also revert the merges that causes issues know.
> 
> By which the main branch will be set to stable mode,

.

**Comment by mansiruhil13** [comment]
but some of them assigned recently for improvements.

**Comment by Shariq2003** [comment]
> but some of them assigned recently for improvements.

So mam, know what should I do.

**Comment by mansiruhil13** [comment]
> > but some of them assigned recently for improvements.
> 
> So @mansiruhil13 mam, what should I do know, as the main branch contains conflicts
> 
> Like my PR is ready but causes happened by main branch

in your branch, toggle and translator there?

**Comment by mansiruhil13** [comment]
Screenshot 2024-10-14 223708
and conflicts also there in this pr

**Pull request closed without merging**
