### PR TITLE
Update login.css

### PR DESCRIPTION
**Pull request by sakshamsaraf23**
i fixed the background of the login page
now it looks like this:
Screenshot 2024-10-05 174921
this solves #126

### CODE REVIEW

**Comment by mansiruhil13** [comment]
merged, but no changes seen in deployment. can you check?

**Comment by sakshamsaraf23** [comment]
no changes were there in the deployement idk what's the problem is ,tell me where are u deploying the website?

**Comment by sakshamsaraf23** [comment]
> merged, but no changes seen in deployment. can you check?

@mansiruhil13 mam do change the label name from "gssoc-extd" to "gssoc-ext" so that our valuable contribution can count

**Comment by sakshamsaraf23** [comment]
@mansiruhil13 mam do change the label name from "gssoc-extd" to "gssoc-ext"(all in small) so that our valuable contribution can count

**Pull request merged**
