### PR TITLE
Modify the teams section

### PR DESCRIPTION
**Pull request by kanCHI-Singhal**
On clicking on the teams page the team details of a specific group in now visible.

### CODE REVIEW

**Comment by mansiruhil13** [comment]
resolve conflicts in pr. and issue no??

**Comment by kanCHI-Singhal** [comment]
Hey actually i am new to github , so i dont know how to resolve conflicts. can you please help me to resolve them.

**Comment by mansiruhil13** [comment]
can you share screenshot or recording of output? as there are few changes done. if i merged this pr, it will create blunder

**Comment by kanCHI-Singhal** [comment]
ok i am sharing the recording of output

**Comment by kanCHI-Singhal** [comment]
Uploading Team — Mozilla Firefox 2024-10-19 11-04-28.mp4…

**Comment by kanCHI-Singhal** [comment]
https://github.com/user-attachments/assets/9a5a0795-1f53-4b2b-bcf6-7114233d6a43

**Pull request closed without merging**
