### PR TITLE
styling of contact box

### PR DESCRIPTION
**Pull request by Anju-Narnolia**
styling of contact box is not according to the theme. green and purple color were used. color changes  according to themes

### CODE REVIEW

**Comment by mansiruhil13** [comment]
screenshot??

**Comment by mansiruhil13** [comment]
screenshot??

**Comment by mansiruhil13** [comment]
issue number??

**Comment by Anju-Narnolia** [comment]
#339

**Comment by Anju-Narnolia** [comment]
please review my PR and merge it

**Pull request closed without merging**
