### PR TITLE
Added Newsletter Valiadation | Toast Alerts | Smoth Scrolling | Issue #444

### PR DESCRIPTION
**Pull request by Shariq2003**
I have added the follwing :-

1. Email Validation in Newsletter.
2. Toast Alert Notification Newsletter.
3. Smooth Scrolling for BackToTop Button.
4. Login and SignUp page Email Validation.
4. Login and SignUp page Taost Alerts for Success and Failure.
5. I also clean the multiple-written code and the index.html file by removing the styling and adding it to the index.css file for better code understanding for new developers.

Completed #444 

https://github.com/user-attachments/assets/226c35df-6f77-4c27-947b-780bdcb552ea

### CODE REVIEW

**Comment by Shariq2003** [comment]
No conflicts

**Comment by Shariq2003** [comment]
@mansiruhil13 mam, please review this and merge, its in pending state since 4days

**Comment by mansiruhil13** [comment]
there are conflicts. resolve!! and navbar is changed. so can you review your code again??

**Comment by Shariq2003** [comment]
@mansiruhil13 mam, please merge now

**Comment by Shariq2003** [comment]
@mansiruhil13 mam, please review and merge

**Comment by Shariq2003** [comment]
@mansiruhil13 mam, please review this

**Comment by Shariq2003** [comment]
@mansiruhil13 mam ?

**Comment by Shariq2003** [comment]
@mansiruhil13 please review and merge this.

**Comment by Shariq2003** [comment]
@MastanSayyad sir please review and merge this

**Review by MastanSayyad — APPROVED** [review]

**Pull request merged**
