### PR TITLE
add: 404 page

### PR DESCRIPTION
**Pull request by hamzathul**
Added 404 page. a custom 404 error page to improve user experience by guiding visitors back to useful content when encountering broken links. It enhances site navigation, professionalism, and SEO handling for missing pages.

Screenshot from 2024-10-08 14-38-39

### CODE REVIEW

**Comment by mansiruhil13** [comment]
on which page?? what's its use?? issue no??

**Comment by hamzathul** [comment]
issue number 424.

This pull request adds a 404.html page for GitHub Pages, which handles cases when users visit a non-existent URL or search for a custom URL. Instead of showing a default error, the custom page helps redirect users back to relevant content, improving navigation and overall user experience on the site

**Comment by mansiruhil13** [comment]
> issue number 424.
> 
> This pull request adds a 404.html page for GitHub Pages, which handles cases when users visit a non-existent URL or search for a custom URL. Instead of showing a default error, the custom page helps redirect users back to relevant content, improving navigation and overall user experience on the site

actually its' not the issue. i can't merge, sorry

**Comment by mansiruhil13** [comment]
> > issue number 424.
> > This pull request adds a 404.html page for GitHub Pages, which handles cases when users visit a non-existent URL or search for a custom URL. Instead of showing a default error, the custom page helps redirect users back to relevant content, improving navigation and overall user experience on the site
> 
> actually its' not the issue. i can't merge, sorry

that github page 404 is error, when click on home page it returns 404, instead it should open the home page

**Pull request closed without merging**
