### PR TITLE
Confirm sign up

### PR DESCRIPTION
**Pull request by Ishika-Gupta06**
issue #711 

The success message is displayed using an alert box after the user successfully signs up.

### CODE REVIEW

**Comment by mansiruhil13** [comment]
there are conflicts, resolve

**Comment by mansiruhil13** [comment]
can you share screenshot or recording

**Comment by mansiruhil13** [comment]
> can you share screenshot or recording

..

**Comment by Ishika-Gupta06** [comment]
Screenshot 2024-10-15 202643

**Pull request merged**
