### PR TITLE
Fixed the icon boxes issue ! #471

### PR DESCRIPTION
**Pull request by Subhajit-2023-44**
Hello PR,
Fixed issue number - #471

https://github.com/user-attachments/assets/0c64d5cb-646c-49f4-bd18-5711f268f3a3

https://github.com/user-attachments/assets/2b5ee7b5-41d0-4914-aa02-ca789d5053e0

https://github.com/user-attachments/assets/0e9a7751-6d14-49b2-a5af-5dd126602512

& I also fixed this issue in "Team" page !
Issue -

https://github.com/user-attachments/assets/15e9ca4a-f5ab-42c0-87d8-2717abb3ec77

Issue Fixed !

https://github.com/user-attachments/assets/3eceed63-fcf9-4e00-a549-7623002263fa

@mansiruhil13

### CODE REVIEW

**Comment by Subhajit-2023-44** [comment]
@mansiruhil13

**Review by MastanSayyad — COMMENTED** [review]
CSS changes, reducing to level 2 (it is mostly level 1 but as you have not scored much on the leaderboard I made it 2)

Dont be discouraged, i recommend you to do postman challenge so that you can get 500 points on the leaderboard easily.

**Comment by Subhajit-2023-44** [comment]
> CSS changes, reducing to level 1 as you are top Contributor
> 
> @Subhajit-2023-44

@MastanSayyad ok sir🙏🏻 I don't deserve level 3 for this😔, you and another project manager🙏🏻 remove some of my levels🤧 ok..


https://github.com/user-attachments/assets/f6408c86-f2b0-40c2-b1d5-edfd951e39a0



but sir can you kindly give me level 3 for this? He gave me just level 1, Is that correct? 😭

Please🥺, I would be very grateful if you could give me level 3 for this.. 


Thank You 🙏🏻

**Review by MastanSayyad — COMMENTED** [review]
Hi @Subhajit-2023-44  These are minimal changes, 


image

Here you have just entered one extra line and added `align-content: center;` ` justify-items: stretch;` `justify-content: center;` `align-items: stretch` 

image

And here too, here you added one extra line above and one below while the changes are none, except adjusting `overflow-x` with `none from` `hidden`

image


Here are no changes only added gap: 22px from 20px which is minimal change

image

you are rank 12 and a top contrinbutor, these changes will not justify level 3

image

**Comment by MastanSayyad** [comment]
> > CSS changes, reducing to level 1 as you are top Contributor
> > @Subhajit-2023-44
> 
> @MastanSayyad ok sir🙏🏻 I don't deserve level 3 for this😔, you and another project manager🙏🏻 remove some of my levels🤧 ok..
> 
>  Untitled.video.-.Made.with.Clipchamp.95.mp4 
> but sir can you kindly give me level 3 for this? He gave me just level 1, Is that correct? 😭
> 
> Please🥺, I would be very grateful if you could give me level 3 for this..
> 
> Thank You 🙏🏻

Sure @Subhajit-2023-44 send me the PR link, I'll review it and add level 3, thank you!

**Comment by Subhajit-2023-44** [comment]
> Hi @Subhajit-2023-44 These are minimal changes,
> 
> image
> 
> Here you have just entered one extra line and added `align-content: center;` ` justify-items: stretch;` `justify-content: center;` `align-items: stretch`
> 
> image
> 
> And here too, here you added one extra line above and one below while the changes are none, except adjusting `overflow-x` with `none from` `hidden`
> 
> image
> 
> Here are no changes only added gap: 22px from 20px which is minimal change
> 
> image
> 
> you are rank 12 and a top contrinbutor, these changes will not justify level 3
> 
> image



Yes sir I totally agree with you.. 🙏🏻

Screenshot 2024-10-27 133104

**Comment by Subhajit-2023-44** [comment]
> > > CSS changes, reducing to level 1 as you are top Contributor
> > > @Subhajit-2023-44
> > 
> > 
> > @MastanSayyad ok sir🙏🏻 I don't deserve level 3 for this😔, you and another project manager🙏🏻 remove some of my levels🤧 ok..
> > Untitled.video.-.Made.with.Clipchamp.95.mp4
> > but sir can you kindly give me level 3 for this? He gave me just level 1, Is that correct? 😭
> > Please🥺, I would be very grateful if you could give me level 3 for this..
> > Thank You 🙏🏻
> 
> Sure @Subhajit-2023-44 send me the PR link, I'll review it and add level 3, thank you!


@MastanSayyad okay sir,

link - https://github.com/iamrahulmahato/master-web-development/pull/1501#issue-2600197042

**Comment by MastanSayyad** [comment]
@Subhajit-2023-44 done ✅

**Comment by Subhajit-2023-44** [comment]
> @Subhajit-2023-44 done ✅

Thank You sir 🙏🏻🙏🏻

**Comment by Subhajit-2023-44** [comment]
@MastanSayyad Sir🙏🏻 kindly review these 5 PR and add level 3, I think I deserve level 3 because I have added new features✨ in all of them but they didn't give me level 3 and also didn't give any reply.. 😭😭

Sir please 🙏🏻, I would be very grateful if you could give me level 3... 🥺

He gave me just level 1 😭

https://github.com/iamrahulmahato/master-web-development/pull/1786#issue-2616472290

https://github.com/iamrahulmahato/master-web-development/pull/1842#issue-2616754363

https://github.com/iamrahulmahato/master-web-development/pull/1953#issue-2620920535

He gave me level 2 🙁

https://github.com/vishanurag/Canvas-Editor/pull/1070#issue-2620998624

https://github.com/vishanurag/Canvas-Editor/pull/1011#issue-2618093554


Thank you

**Comment by Subhajit-2023-44** [comment]
@MastanSayyad Sir🙏🏻 kindly review at least these 3 PR and add level 3, 

He gave me just level 1 😭

https://github.com/iamrahulmahato/master-web-development/pull/1786#issue-2616472290

https://github.com/iamrahulmahato/master-web-development/pull/1842#issue-2616754363

https://github.com/iamrahulmahato/master-web-development/pull/1953#issue-2620920535

**Comment by MastanSayyad** [comment]
@Subhajit-2023-44 updated the levels and please dont ask for level 3 for such changes, it can only have level 2

**Comment by Subhajit-2023-44** [comment]
> @Subhajit-2023-44 updated the levels and please dont ask for level 3 for such changes, it can only have level 2

Thank you sir🙏🏻 for giving at least level 2 (he gave me just level 1😭)

Okay sir 🙏🏻

**Comment by Subhajit-2023-44** [comment]
> @Subhajit-2023-44 updated the levels and please dont ask for level 3 for such changes, it can only have level 2

Sorry to bother you again 🙏🏻😞

@MastanSayyad sir can I deserve level 3 for this?  I added a new feature profile page..

Screenshot 2024-11-09 154238
Screenshot 2024-11-09 154255

**Comment by Subhajit-2023-44** [comment]
@MastanSayyad Sir🙏🏻 kindly review these PR's and add level 3,


https://github.com/YadavAkhileshh/Alien-Invasion-Defense/pull/724#issue-2644257049
image
 
https://github.com/ankit071105/Ticket-Booking/pull/936#issue-2631149126 
image

https://github.com/mansiruhil13/Bobble-AI/pull/1172#issue-2635341528
image
 
https://github.com/vishanurag/Canvas-Editor/pull/1181#issue-2631225498
image

https://github.com/ankit071105/Ticket-Booking/pull/1081#issue-2642312490
image

**Comment by Subhajit-2023-44** [comment]
@MastanSayyad sir 🙏🏻

**Comment by MastanSayyad** [comment]
@Subhajit-2023-44 already added + some PRs are similar so for that I cant give level 3

**Comment by Subhajit-2023-44** [comment]
> @Subhajit-2023-44 already added + some PRs are similar so for that I cant give level 3

@MastanSayyad Thanks a lot sir, 🙏🏻🥰

Sir please merge this PR - 

https://github.com/ankit071105/Ticket-Booking/pull/1081#issue-2642312490

**Comment by Subhajit-2023-44** [comment]
Thank you sir @MastanSayyad

**Pull request merged**
