### PR TITLE
Update CSS file

### LINKED ISSUE #702: [Feature Request]: Improve the look of the website
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Add or modify the features of the page of the website

Please assign me  this issue

### Use Case

Use Css properties

### Benefits

To make more eye catching

### Priority

Low

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

### PR DESCRIPTION
**Pull request by Dipanita45**
---
name: Pull_request_TEMPLATE.yml
about: use this template for creation of pull requests
title: ' #702 
labels: '' Gossco extd,  level 2
assignees: 

## Description
<-- Add or update the css to add new feature to make more attractive. -->

- Fixes #702 

## Type of Change

- [no] Bug fix (non-breaking change which fixes an issue)
- [yes] New feature (non-breaking change which adds functionality)
- [no] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [no] Documentation update

## Checklist

- [yes] I have read the contributing document.
- [yes] I have performed a self-review of my own code.
- [yes] I have commented my code, particularly in hard-to-understand areas.
- [ no] I have added necessary tests to ensure my changes are effective.
- [yes] New and existing unit tests pass locally with my changes.
- [no] Any dependent changes have been merged and published in downstream modules.

Please review my pull request and approved it and label it
@mansiruhil13 
Thank you

### CODE REVIEW

**Comment by mansiruhil13** [comment]
can you share output screenshot or any recording??

**Comment by Dipanita45** [comment]
Screenshot 2024-10-30 201543
 Please merge my pull request and label me 
@mansiruhil13

**Comment by Dipanita45** [comment]
Please review my pull request and approved it and label it
@mansiruhil13

**Comment by Dipanita45** [comment]
Please review my pull request and approved it and label it
@mansiruhil13

**Comment by Dipanita45** [comment]
Please review my pull request and approved it and label it level 2
@mansiruhil13
As today is the last day

**Pull request closed without merging**
