### PR TITLE
logo added

### PR DESCRIPTION
**Pull request by shreyad2806**
Added logo in all the pages
Please assign the gssoc and hactoberfest tag.
Please give level2

### CODE REVIEW

**Comment by shreyad2806** [comment]
Please merge my pr

**Comment by mansiruhil13** [comment]
logo added already, you can check deployment

**Comment by shreyad2806** [comment]
Its not showing in my merged lists

**Comment by shreyad2806** [comment]
Heyy, sorry to bother you but maybe as its not showing in assign therefore even after merging it is not showing in my leaderboard could you please assign this in my name and then merge

**Comment by mansiruhil13** [comment]
which logo??

**Comment by shreyad2806** [comment]
You have merged the pr just assign it with my name

**Comment by mansiruhil13** [comment]
> You have merged the pr just assign it with my name

but there is no issue for logo.

**Comment by shreyad2806** [comment]
> > You have merged the pr just assign it with my name
> 
> but there is no issue for logo now.

#162 
open the issue then assign the issue

**Pull request closed without merging**
