### PR TITLE
Redirect_to_Homepage By Clicking on Logo

### PR DESCRIPTION
**Pull request by RithwikBejadi**
The Problem is solved, In each and every Page the main logo and text redirects to the main page.

### CODE REVIEW

**Comment by mansiruhil13** [comment]
issue no??

**Comment by mansiruhil13** [comment]
screenrecording or screenshot??

**Comment by RithwikBejadi** [comment]
https://github.com/user-attachments/assets/e0aefacf-7dc3-49d9-8cb4-b53825e34688


https://github.com/user-attachments/assets/524a2f82-3f5b-4c0f-b78c-d9bdcd71bd48


https://github.com/user-attachments/assets/502ae57a-3c31-4a65-b974-0087162fcf04


https://github.com/user-attachments/assets/7f00194c-079c-4636-ac54-b4983d965823



It Works Similarly for all the Pages

**Comment by mansiruhil13** [comment]
there are conflicts, resolve

**Comment by mansiruhil13** [comment]
and from home page to driver availability page???

**Comment by RithwikBejadi** [comment]
> and from home page to driver availability page???

I'm Sorry But it wasn't mentioned in the issue
I tried to solve issue #715

**Comment by RithwikBejadi** [comment]
> issue no??

#715

**Comment by RithwikBejadi** [comment]
@mansiruhil13 please review the changes
mention any changes to be made further

**Comment by mansiruhil13** [comment]
> @mansiruhil13 please review the changes mention any changes to be made further

can you made some changes acc to new one? as navbar changed

**Comment by RithwikBejadi** [comment]
> > @mansiruhil13 please review the changes mention any changes to be made further
> 
> can you made some changes acc to new one? as navbar changed

Sure

**Comment by RithwikBejadi** [comment]
> > @mansiruhil13 please review the changes mention any changes to be made further
> 
> can you made some changes acc to new one? as navbar changed

Could you please review the latest commits.
I updated it again.

https://github.com/user-attachments/assets/6ff8739e-2555-41d7-80f5-c61c18c082e7


https://github.com/user-attachments/assets/4206771f-0b71-4aef-8704-084248edbed0


https://github.com/user-attachments/assets/7525b402-d6b9-41c3-8a8e-12fff9d66984

**Comment by mansiruhil13** [comment]
there are conflicts, resolve
Screenshot 2024-10-15 191953

**Comment by mansiruhil13** [comment]
also landing page added. change into your code

**Comment by RithwikBejadi** [comment]
> also landing page added. change into your code

Okay

**Pull request closed without merging**
