### PR TITLE
Implemented Express Backend and Login,Signup functionality

### LINKED ISSUE #443: [Feature Request]:  Implement Signup and Login (backend)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Backend is not yet created for this website, so i will create an express js app and work on implementing login and signup. I will write the entire logic, comment it which should be uncommented when the PA creates a mongo DB server and configures it in the server as i cant create the DB (it should be created only by project admin for security purposes). I will also use bcrypt js and jwt.

### Use Case

Users will be able to create an account and login easily. 

### Benefits

_No response_

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

### PR DESCRIPTION
**Pull request by devarsheecodess**
https://github.com/user-attachments/assets/e9908e2a-b840-49ab-97e5-b2fb9b7ae8ec

For Frontend testing, i have temporarily kept username as "username" and password as "123456"
image
I have added proper comments in frontend as well as backend code so that after mongo DB is connected, we can use it.

Also tested the backend using postman
login-working
signup-working

Fixes #443

### CODE REVIEW

**Comment by mansiruhil13** [comment]
Screenshot 2024-10-09 230235
resolve conflicts and second, already merged pr for password strength in the page. can you make changes acc to that. so that, no changes or issues occurs further?

**Comment by devarsheecodess** [comment]
@mansiruhil13 done

**Comment by devarsheecodess** [comment]
wait

**Comment by devarsheecodess** [comment]
@mansiruhil13 merge before more conflicts occur 🥹

**Comment by devarsheecodess** [comment]
@mansiruhil13 this was level3

**Comment by devarsheecodess** [comment]
@mansiruhil13  this was level3
Check #472 issue

**Comment by devarsheecodess** [comment]
@mansiruhil13  this was level3
Check #443

**Comment by devarsheecodess** [comment]
@mansiruhil13  this was level3
Check #443

**Pull request merged**
