### PR TITLE
Fixed double icon box issue in Team page ! #610

### PR DESCRIPTION
**Pull request by Subhajit-2023-44**
Hello PR,
Fixed issue number - #610

Screenshot 2024-10-12 135647
Screenshot 2024-10-12 140019

@mansiruhil13

### CODE REVIEW

**Comment by Subhajit-2023-44** [comment]
@mansiruhil13 PA why did you close my PR without merging?   I fixed the issue properly.      

See the problem is still not completely solved..
Screenshot 2024-10-12 165805

**Comment by 4F24L** [comment]
@mansiruhil13 This issue still exists. I think reopening this PR can help.

**Comment by Subhajit-2023-44** [comment]
@mansiruhil13

**Comment by Subhajit-2023-44** [comment]
@mansiruhil13 ??

**Comment by Subhajit-2023-44** [comment]
@mansiruhil13

**Comment by mansiruhil13** [comment]
> @mansiruhil13

already done. 
Screenshot 2024-10-14 232852

**Comment by mansiruhil13** [comment]
> @mansiruhil13

done already, that's why i closed it.

**Comment by Subhajit-2023-44** [comment]
> > @mansiruhil13
> 
> already done. Screenshot 2024-10-14 232852


See the problem is still not completely solved.. -

Screenshot 2024-10-12 165805

**Comment by Subhajit-2023-44** [comment]
@mansiruhil13

**Comment by mansiruhil13** [comment]
> > > @mansiruhil13
> > 
> > 
> > already done. Screenshot 2024-10-14 232852
> 
> See the problem is still not completely solved.. -
> 
> Screenshot 2024-10-12 165805

but there are few changes, translator has been added.

**Comment by Subhajit-2023-44** [comment]
> > > > @mansiruhil13
> > > 
> > > 
> > > already done. Screenshot 2024-10-14 232852
> > 
> > 
> > See the problem is still not completely solved.. -
> > Screenshot 2024-10-12 165805
> 
> but there are few changes, translator has been added.

@mansiruhil13 okay do I fix it again ??

**Comment by mansiruhil13** [comment]
you can make changes into the code

**Comment by Subhajit-2023-44** [comment]
> you can make changes into the code

okay

**Comment by Subhajit-2023-44** [comment]
@mansiruhil13 I have create a new pull request #752 for this issue please merge and add level 1

**Pull request closed without merging**
