### PR TITLE
Nav_to_Homepage

### PR DESCRIPTION
**Pull request by RithwikBejadi**
## Description

- Fixes # (issue) Redirects to homepage on clicking on logo and title text

## Screenrecordings

https://github.com/user-attachments/assets/79fcd941-2aa1-4363-b051-7edbcbead1ae

https://github.com/user-attachments/assets/290d7f30-610a-438f-bdda-6a196928e05b

https://github.com/user-attachments/assets/2fbe1d6c-c185-4b3f-9aae-cb6a91fc8724

https://github.com/user-attachments/assets/499cdf9e-f3c2-42c5-9afb-87f8d17a8030

https://github.com/user-attachments/assets/1bfb3c8c-f48a-4ec5-9be1-a6ed68966e24

https://github.com/user-attachments/assets/b55b5f98-2cff-4438-80f4-8cfd87ffb667

https://github.com/user-attachments/assets/39e8f3f7-c5fa-4d3c-91e3-f1304e241bcc

https://github.com/user-attachments/assets/34c6a19b-98aa-401a-8505-962e3cb4fc20

https://github.com/user-attachments/assets/f9f82292-fb29-443f-ba7e-8688cbeff28b

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

- [x] I have read the contributing document.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have added necessary tests to ensure my changes are effective.
- [x] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published in downstream modules.

## Additional Information

---
Please Merge it if there are no problems for now
Further changes will be made when future Changes will happen to the website
(Will be pulled again when the website or the UI Changes)

### CODE REVIEW

**Comment by RithwikBejadi** [comment]
@mansiruhil13 
If any further changes will takeplace i will pull again for same problem
If there are no issues with it, please merge it (Comment for any existing changes)
Thankyou

**Comment by mansiruhil13** [comment]
Screenshot 2024-10-19 194137
symbols added

**Comment by RithwikBejadi** [comment]
> Screenshot 2024-10-19 194137
> symbols added

I didn't get u...;)

**Comment by RithwikBejadi** [comment]
> Screenshot 2024-10-19 194137 symbols added

But the home and title would also be helpful and convinient

**Pull request closed without merging**
