### PR TITLE
Contributors page created

### LINKED ISSUE #1185: [Feature Request]: Ading a contributors page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would make a new webpage dedicated to the contributors of this project which displays the stats of contribution on this project by the contributors, i would also add cool animation when contributors cards are hovered.

### Use Case

This would show the stats of this project

### Benefits

_No response_

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

### PR DESCRIPTION
**Pull request by Son7c**
---
name: Pull_request_TEMPLATE.yml
about: use this template for creation of pull requests
title: '[FIX/Feat] '
labels: ''
assignees: ''

---
name: Pull Request Template

## Description

- Fixes #1185 

## Screenshots (if applicable)

https://github.com/user-attachments/assets/d2d8ba7f-16a0-4073-97d7-79101c8754a9

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

- [x] I have read the contributing document.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have added necessary tests to ensure my changes are effective.
- [x] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published in downstream modules.

## Additional Information

---

### CODE REVIEW

**Comment by Son7c** [comment]
@mansiruhil13 Please merge this PR with a higher level

**Comment by mansiruhil13** [comment]
can you review you code again? actually profile page and web app changes have added recently. please otherwise this pr makes blunder

**Comment by Son7c** [comment]
@mansiruhil13 I synced my repo to the latest commit. Please merge this PR with level 3 tag as i made the entire page and added functionality.

**Comment by mansiruhil13** [comment]
> @mansiruhil13 I synced my repo to the latest commit. Please merge this PR with level 3 tag as i made the entire page and added functionality.

edit profile section have been added recently. if this pr merged then that have been removed

**Comment by Son7c** [comment]
@mansiruhil13 Can you please mention level 3 tag?

**Comment by Son7c** [comment]
@mansiruhil13 Please tag level3, worked hard adding functionality and animation.

**Pull request merged**
