### PR TITLE
issue #764 Resolved

### PR DESCRIPTION
**Pull request by KrishnaMohanty08**
1. Resolved the Navbar folding issue 
2.  deleted the translate unnecessary translate button 
3. fixed the dark mode in nav bar
before
image
after
image

### CODE REVIEW

**Comment by KrishnaMohanty08** [comment]
@mansiruhil13 could you please review

**Comment by mansiruhil13** [comment]
navbar has changed.

**Comment by mansiruhil13** [comment]
can you make changes in your code?

**Comment by KrishnaMohanty08** [comment]
my bad, there's nothg according to the issue i had created ....it had been resolved

**Comment by KrishnaMohanty08** [comment]
> can you make changes in your code? acc to new navbar

as it can't be merged could please write an approving review on this it could be a great help for me @mansiruhil13

**Pull request merged**
