### PR TITLE
Updated grid section

### PR DESCRIPTION
**Pull request by Sahitya317**
One prominent feature was missing from the grid section . Added that in same format
name:  Updated Grid Section

## Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

## Checklist

- [x] I have read the contributing document.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have added necessary tests to ensure my changes are effective.
- [x] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published in downstream modules.

## Additional Information

---

### CODE REVIEW

**Comment by mansiruhil13** [comment]
issue no?? and output screenshot??

**Comment by Sahitya317** [comment]
> issue no?? and output screenshot??

#1193 
Screenshot 2024-11-07 224337

**Comment by mansiruhil13** [comment]
and can you elaborate what changes have you made?

**Comment by Sahitya317** [comment]
> > > issue no?? and output screenshot??
> > 
> > 
> > #1193 Screenshot 2024-11-07 224337
> 
> i am asking about issue no? not pr no

#1220..this change comes under feature request .... In the monitoring section (grid)earlier there were only 5 boxes ...now driver performance management is also added(by me) ..... so the blank space there got filled and all boxes are in alignment now

**Pull request merged**
