### PR TITLE
feeback improved and functional now

### PR DESCRIPTION
**Pull request by 1ShahidBashir**
---
name: feeback improved and functional now
about: use this template for creation of pull requests
title: '[FIX/Feat] '
labels: ''
assignees: ''

---
name: Pull Request Template

## Description

feedback form made functional and improved
- Fixes # (issue)

## Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

- [x] I have read the contributing document.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have added necessary tests to ensure my changes are effective.
- [x] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published in downstream modules.

## Additional Information

---
image

### CODE REVIEW

**Comment by 1ShahidBashir** [comment]
@mansiruhil13 please check my PR

**Comment by 1ShahidBashir** [comment]
@mansiruhil13 please check this PR!!!

**Comment by 1ShahidBashir** [comment]
@mansiruhil13 check this please

**Comment by mansiruhil13** [comment]
navbar has changed on all pages. can you make the similar one? please review your code again for that.

**Comment by 1ShahidBashir** [comment]
@mansiruhil13 yeah let me try

**Comment by 1ShahidBashir** [comment]
@mansiruhil13 
image
Please check the PR now!

**Comment by 1ShahidBashir** [comment]
@mansiruhil13 check now

**Comment by 1ShahidBashir** [comment]
@mansiruhil13 check the PR please

**Pull request closed without merging**
