### PR TITLE
Ashu flask organise Converted the site into flask web app

### PR DESCRIPTION
**Pull request by ashupal86**
#523  this is pr for changing the project structure from static to flask.
Do read the changes.md and run.md to understand the changes.

### CODE REVIEW

**Comment by mansiruhil13** [comment]
Screenshot 2024-10-12 160939
there are conflicts. resolve

**Comment by mansiruhil13** [comment]
> Screenshot 2024-10-12 160939 there are conflicts. resolve

and chatbot feature and some other features added recently so do changes accordingly

**Comment by ashupal86** [comment]
these cannot be resolved until rewrite them from scratch as the code reusability in static website is 0% and I will try to resolve them if I can get more details about them.
you can see the index.html and layout.html from your repo and my forked repo for chnages that hav been made for reference.
These are conflicts because these files are moved to a differnent folder within the applcicaton as you can see so it is finding the files which can not be found in root folder so the conflicts can not be resolved.
Goto:app/templates to see all these files in my repo

**Comment by ashupal86** [comment]
[reply to features added recently](https://github.com/mansiruhil13/Bobble-AI/pull/631#issuecomment-2408519118  )
We will have to add them in their respective file so you can create another bracnh in which you can merege the request.
Most of the devs are just fixing and adding new features in it because it is an easy repo to contribute in because of the static files.

**Comment by ashupal86** [comment]
I also cannot fetch the latest files as this will also remove all the changes that i have made.

**Comment by ashupal86** [comment]
If you merge my branch  into main all the devs have to rewrite thier features according to project structure.
If I have to add all the features and get bugs fixed this will take months long as all are contirbuting and theire pr's are getting merged.

**Comment by mansiruhil13** [comment]
> If you merge my branch into main all the devs have to rewrite thier features according to project structure. If I have to add all the features and get bugs fixed this will take months long as all are contirbuting and theire pr's are getting merged.

unable to merge because there are conflicts in this branch

**Comment by ashupal86** [comment]
okay it is completely on you.
Thank you.

**Pull request closed without merging**
