### PR TITLE
Added 3 new FAQ questions

### PR DESCRIPTION
**Pull request by Monojit-Pal**
Added three new frequently asked questions (FAQs) to the ambulance monitoring system's FAQ section. These questions focus on ambulance cancellation, safety instructions, and handling technical issues related to the tracking system.
Screenshot 2024-10-15 095408
@4F24L

### CODE REVIEW

**Comment by mansiruhil13** [comment]
issue no??

**Comment by Monojit-Pal** [comment]
@mansiruhil13 the issue no. is #661

**Comment by mansiruhil13** [comment]
there are conflicts, resolve

**Comment by mansiruhil13** [comment]
and as landing page is added. can you change into your code. so that this pr doesn't make any blunder

**Comment by Monojit-Pal** [comment]
@mansiruhil13 I will make the necessary changes.

**Pull request closed without merging**
