### PR TITLE
added navbar and darkmode to nearbypage

### PR DESCRIPTION
**Pull request by poojitha-ch**
1)The navbar on everypage is made same and darkmode functonality is added to team page.<br>
image
image<br>
2)Navbar and darkmode is added to nearby page<br>
image
image

### CODE REVIEW

**Comment by mansiruhil13** [comment]
issue no?

**Comment by mansiruhil13** [comment]
output?

**Comment by poojitha-ch** [comment]
> issue no?

#828

**Comment by poojitha-ch** [comment]
> output?

i had attached the output picture in the above pull request
i added navbar to the nearby page
darkmode functionality to team page and nearby page
and made the navbar consistent across all pages

**Pull request closed without merging**
