### PR TITLE
added password eye button

### PR DESCRIPTION
**Pull request by devarsheecodess**
I have added a functional password eye button which toggles the input password visibility. Attaching a screen recording below.

https://github.com/user-attachments/assets/f907d5b5-6e68-4395-b024-948d5d345b9c

### CODE REVIEW

**Comment by mansiruhil13** [comment]
okay, can you improve ui interface ??

**Comment by devarsheecodess** [comment]
Sure, give me some time

**Comment by devarsheecodess** [comment]
@mansiruhil13 i have done the changes, also if you merge the PR, it would be great if you add gssoc-extd label and then merge my PR :)

**Comment by mansiruhil13** [comment]
can you show outputs?

**Comment by devarsheecodess** [comment]
Here it it and thank you for merging my PR 😊
WhatsApp Image 2024-10-02 at 21 30 22_ef79721f

**Pull request merged**
