### PR TITLE
[FIX] Fixed Issue #787

### PR DESCRIPTION
**Pull request by OmAmar106**
Fixes Issue #787 

Debugged the errors, no more not found pages. As shown in the attached video.

Files changed : index.html , privacy.html

https://github.com/user-attachments/assets/004278ea-3de5-4a84-a548-9f002d706b3e

### CODE REVIEW

**Comment by mansiruhil13** [comment]
there are few changes, chatbot added on all pages. can you check again your code ?

**Comment by OmAmar106** [comment]
> there are few changes, chatbot added on all pages. can you check again your code ?

Yes , synced my PR with them.

**Comment by mansiruhil13** [comment]
> > there are few changes, chatbot added on all pages. can you check again your code ?
> 
> Yes , synced my PR with them.

done or not?

**Comment by OmAmar106** [comment]
> > > there are few changes, chatbot added on all pages. can you check again your code ?
> > 
> > Yes , synced my PR with them.
> 
> done or not?

Done

**Review by MastanSayyad — COMMENTED** [review]
Addes hyperlinks path for files so reducing the labels to `level 1

Please don't be discouraged, i recommend you to do postman challenge so that you can get 500 points on the leaderboard easily.  @OmAmar106

**Pull request merged**
