### PR TITLE
Updated to show existing driver

### PR DESCRIPTION
**Pull request by Pooja3Bhattrai**
Resolved: now it will display that existing drivers is exists.

exist driver

### CODE REVIEW

**Comment by mansiruhil13** [comment]
> Resolved: now it will display that existing drivers is exists.
> 
> exist driver

Screenshot 2024-10-04 005155
in header section, manage status and logout not working

**Comment by Pooja3Bhattrai** [comment]
@mansiruhil13 ,   I went through and checked in file changed section ,  I realised there is no error from my side.

you can also go through and let me know
pls review this file:

url:   https://github.com/mansiruhil13/Bobble-AI/pull/100/files

**Review by mansiruhil13 — COMMENTED** [review]
in header section, manage status and logout not clickable

**Comment by Pooja3Bhattrai** [comment]
@mansiruhil13 ,   hey Mansi

 i only just raised a issue for, duplication of driver names .... so for solving that i just added that features only..

i am not able to understand what you are trying to say  
1. after being made change by me, that is why it is not working or clickable?? 
2. or something else??

**Pull request merged**
