### PR TITLE
added the cursor: pointer property to the card elements in both index…

### PR DESCRIPTION
**Pull request by ritikraj2425**
….html and homepage.html

### CODE REVIEW

**Comment by mansiruhil13** [comment]
output? screenshot?

**Comment by mansiruhil13** [comment]
issue no?

**Comment by ritikraj2425** [comment]
issue no - #868 
WhatsApp Image 2024-10-17 at 22 19 51

**Comment by ritikraj2425** [comment]
> issue no?
issue no -#868
WhatsApp Image 2024-10-17 at 22 19 51

**Comment by mansiruhil13** [comment]
but you are not assigned for the issue? why did you create a pr?

**Pull request closed without merging**
