### PR TITLE
[FIX] FAQ Section Glitches Fixed

### LINKED ISSUE #888: [Bug]: FAQ section is messed up
### Is there an existing issue for this?

- [X] I have searched the existing issues

## FAQ Section Issue

- FAQ answers are double
- FAQ collapsing with jitter
- FAQ collapsing with red background [ WHY ?? ]

### Add Screenshots

Uploading faq issue.mp4…

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

### PR DESCRIPTION
**Pull request by 4F24L**
## FAQ Section Glitches Fixed

- Fixes #888 

image

### CODE REVIEW

**Comment by 4F24L** [comment]
Can you please add at least level 1 to these PRs? As these are the genuine issues that I raised and solved. @MastanSayyad

**Comment by 4F24L** [comment]
I wasn't aware of the proper labeling guidelines in this repo, so I initially labeled every small issue as level 2 or 3. I now understand the correct approach, and moving forward, I'll contribute according to the rules.

**Comment by MastanSayyad** [comment]
@4F24L You should let the Project Admin (PA) handle their responsibilities, as it’s their job to add labels. Just think, if every contributor started doing like this, would it be fair to others?

I hope you'll contribute more fairly from now on.

@mansiruhil13 I haven't heard anything from your side yet. Can you please clarify this situation in your repository? Are you aware of what's going on? Have you been active in the Discord PA channel? Are you staying active in your repo?

**Comment by 4F24L** [comment]
> @4F24L You should let the Project Admin (PA) handle their responsibilities, as it’s their job to add labels. Just think, if every contributor started doing like this, would it be fair to others?
> 
> I hope you'll contribute more fairly from now on.

@MastanSayyad I understand that my actions might seem unfair, but I want to clarify that I wasn't trying to spam or gain scores dishonestly. My intention was to contribute meaningfully, and I followed what I saw in the repository. Most issues were labelled as Level 2 or Level 3, so I did the same without fully understanding the GSSoC rules.

You can check issue #939 titled "NOTICE ⚠️: GSSOC EXtended Program Manager" for more context. I mentioned some of the PRs to explain my reasoning. I realize now that I should have understood the GSSoC criteria better, but I followed the same approach as others PRs that were managed similarly. Moving forward, I will ensure that my contributions align with fair practices and the GSSoC rules.

**Comment by MastanSayyad** [comment]
@4F24L You were not a project admin nor a Mentor, There is no point of were you following what was going on this repo or not

I'm going to reduce all unfair labeling in this PR, therefore I asked the admin to speak about such practice. i announce daily on discord about the guidelines and updates to all PAs and Contributors.

**Comment by 4F24L** [comment]
Okay, I will contribute according to the rules from now on. Can I continue contributing to this project, or should I focus on other projects instead?

**Comment by MastanSayyad** [comment]
@4F24L focus on others, as some contributors caught an eye on your profile so they will label you as a spammer if you keep contributing here

**Pull request merged**
