### PR TITLE
alignment and responsiveness

### PR DESCRIPTION
**Pull request by srishti023**
#686 
I have successfully implement responsiveness in every single page . please review it and if any further improvement needed please let me know else merge it. 
Thankyou!

Before:
Screenshot 2024-10-13 234436
Screenshot 2024-10-15 115150
Screenshot 2024-10-15 115333

After:

Screenshot 2024-10-15 114957
Screenshot 2024-10-15 115113
Screenshot 2024-10-15 115837

### CODE REVIEW

**Comment by mansiruhil13** [comment]
there are conflicts, resolve

**Comment by srishti023** [comment]
I have successfully resolved all the conflicts that were present in the codebase. Additionally, I noticed that in the updated repository the index.html page was not responsive, so I took the initiative to also make it responsive across all devices. 


https://github.com/user-attachments/assets/478970c0-c13e-4812-acb6-f3e69bf3f0f6


https://github.com/user-attachments/assets/90e9175d-8d69-4c90-802e-68fc6dbebf30


Please let me know if you have any feedback or if there are other areas you would like me to focus on.

**Comment by srishti023** [comment]
resolved, please merge.

**Comment by aslams2020** [comment]
This PR has been merged by the GSSoC team 
here - https://github.com/sanjay-kv/Open-source-Practice/pull/1416

 **Don't add labels to it now.**
You'll get the points in the leaderboard update.

**Pull request closed without merging**
