### PR TITLE
Revert "fix: 🐛 Removed the Manual Github pages Build & deploy action"

### PR DESCRIPTION
**Pull request by mansiruhil13**
Reverts mansiruhil13/Bobble-AI#143

### CODE REVIEW

**Comment by yashksaini-coder** [comment]
hi @mansiruhil13 why u revert it ?

**Comment by mansiruhil13** [comment]
> hi @mansiruhil13 why u revert it ?

to make changes in hackoctober fest

**Comment by yashksaini-coder** [comment]
okh can you explain to me what reverting the PR does ?

**Comment by yashksaini-coder** [comment]
> > hi @mansiruhil13 why u revert it ?
> 
> to make changes in hackoctober fest site and pull request successfully merged and closed
@mansiruhil13 
does merging then revert PR changes discards our code or accepts our code into the repo

**Comment by mansiruhil13** [comment]
> okh can you explain to me what reverting the PR does ? and how does hacktoberfest is affected ?

Reverting a PR on GitHub means undoing the changes that the pull request introduced. It brings the code back to how it was before the PR was merged, without deleting the original PR. Instead, a new commit is created to reverse the effects of the merged changes. This is useful if something went wrong after merging the PR or if you need to roll back the changes for any reason.

**Comment by yashksaini-coder** [comment]
> > > hi @mansiruhil13 why u revert it ?
> > 
> > 
> > to make changes in hackoctober fest site and pull request successfully merged and closed
> 
> @mansiruhil13 does merging then revert PR changes discards our code or accepts our code into the repo

so what happens to my code in your project, it's not merged then ??

**Comment by mansiruhil13** [comment]
> > > > hi @mansiruhil13 why u revert it ?
> > > 
> > > 
> > > to make changes in hackoctober fest site and pull request successfully merged and closed
> > 
> > 
> > @mansiruhil13 does merging then revert PR changes discards our code or accepts our code into the repo
> 
> so what happens to my code in your project, it's not merged then ??

Screenshot 2024-10-05 012647

**Comment by mansiruhil13** [comment]
actually i have not much idea

**Comment by yashksaini-coder** [comment]
> > > > > hi @mansiruhil13 why u revert it ?
> > > > 
> > > > 
> > > > to make changes in hackoctober fest site and pull request successfully merged and closed
> > > 
> > > 
> > > @mansiruhil13 does merging then revert PR changes discards our code or accepts our code into the repo
> > 
> > 
> > so what happens to my code in your project, it's not merged then ??
> 
> Screenshot 2024-10-05 012647

okh i don't understand this but still if you think it is okh then I have no problems.

**Comment by yashksaini-coder** [comment]
but is it not problem for you to have many failed workflow actions, piling up. It is not good right ?

@mansiruhil13

**Comment by mansiruhil13** [comment]
> but is it not problem for you to have many failed workflow actions in the repo actions tab, piling up. It is not good right ?
> 
> @mansiruhil13

i don't know about this

**Pull request merged**
