### PR TITLE
Fix: Centered the logo

### PR DESCRIPTION
**Pull request by Karnmayank07**
This pull request addresses the issue of the logo being aligned to the left. The fix involves updating the CSS to center the logo within the header or navigation bar. I ensured that the logo remains properly centered across different screen sizes, improving the visual balance and making the layout cleaner and more user-friendly.

Screenshot 2024-10-03 012159

### CODE REVIEW

**Comment by mansiruhil13** [comment]
can you change logo for ambulance live tracking system. bobble AI is repository random name

**Comment by Karnmayank07** [comment]
> can you change logo for ambulance live tracking system. bobble AI is repository random name

are you talking about  
Screenshot 2024-10-03 013422
 ?

**Comment by mansiruhil13** [comment]
> > can you change logo for ambulance live tracking system. bobble AI is repository random name
> 
> are you talking about Screenshot 2024-10-03 013422 ?

yes, otherwise you can take any logo for ambulance tracking system but not for bobble ai

**Comment by Karnmayank07** [comment]
> > > can you change logo for ambulance live tracking system. bobble AI is repository random name
> > 
> > 
> > are you talking about Screenshot 2024-10-03 013422 ?
> 
> yes, otherwise you can take any logo for ambulance tracking system but not for bobble ai

just tell aboutthe logo in detailwhat i shoud add in the logo

**Comment by mansiruhil13** [comment]
> > > > can you change logo for ambulance live tracking system. bobble AI is repository random name
> > > 
> > > 
> > > are you talking about Screenshot 2024-10-03 013422 ?
> > 
> > 
> > yes, otherwise you can take any logo for ambulance tracking system but not for bobble ai
> 
> just tell aboutthe logo in detailwhat i shoud add in the logo

logo for **ambulance monitoring system**
Description: that notifies patients of nearby hospitals and the estimated time of arrival of the ambulance. It provides hospitals and ambulance drivers with critical information such as the patient’s location and enables effective GPS route management via real-time traffic information on scheduled routes.

**Comment by Karnmayank07** [comment]
> > > > > can you change logo for ambulance live tracking system. bobble AI is repository random name
> > > > 
> > > > 
> > > > are you talking about Screenshot 2024-10-03 013422 ?
> > > 
> > > 
> > > yes, otherwise you can take any logo for ambulance tracking system but not for bobble ai
> > 
> > 
> > just tell aboutthe logo in detailwhat i shoud add in the logo
> 
> logo for **ambulance monitoring system** Description: that notifies patients of nearby hospitals and the estimated time of arrival of the ambulance. It provides hospitals and ambulance drivers with critical information such as the patient’s location and enables effective GPS route management via real-time traffic information on scheduled routes.

ok got it  i can make

**Comment by Karnmayank07** [comment]
> > > > > can you change logo for ambulance live tracking system. bobble AI is repository random name
> > > > 
> > > > 
> > > > are you talking about Screenshot 2024-10-03 013422 ?
> > > 
> > > 
> > > yes, otherwise you can take any logo for ambulance tracking system but not for bobble ai
> > 
> > 
> > just tell aboutthe logo in detailwhat i shoud add in the logo
> 
> logo for **ambulance monitoring system** Description: that notifies patients of nearby hospitals and the estimated time of arrival of the ambulance. It provides hospitals and ambulance drivers with critical information such as the patient’s location and enables effective GPS route management via real-time traffic information on scheduled routes.

i am having some issues while making logo not getting  enough elements as free and i dont have any paid software you can assign  this issue to someone else   i can do other stuffs in code and all 
and why fixed centred the logo is not merged can you tell me do i need to do or add  more thing ?

**Comment by mansiruhil13** [comment]
you can add this logo as well

> > can you change logo for ambulance live tracking system. bobble AI is repository random name
> 
> are you talking about Screenshot 2024-10-03 013422 ?

**Comment by Karnmayank07** [comment]
> you can add this logo as well
> 
> > > can you change logo for ambulance live tracking system. bobble AI is repository random name
> > 
> > 
> > are you talking about Screenshot 2024-10-03 013422 ?
ok done assigned it to me i am doing it

**Comment by mansiruhil13** [comment]
> > you can add this logo as well
> > > > can you change logo for ambulance live tracking system. bobble AI is repository random name
> > > 
> > > 
> > > are you talking about Screenshot 2024-10-03 013422 ?
> > > ok done assigned it to me i am doing it
> > > can you add level of gssoc- extended and hacktoberfest too in labels

Image not shown?

**Comment by Karnmayank07** [comment]
> > > you can add this logo as well
> > > > > can you change logo for ambulance live tracking system. bobble AI is repository random name
> > > > 
> > > > 
> > > > are you talking about Screenshot 2024-10-03 013422 ?
> > > > ok done assigned it to me i am doing it
> > > > can you add level of gssoc- extended and hacktoberfest too in labels
> 
> Image not shown?

wait i am doing and creating pull request

**Pull request merged**
