### PR TITLE
fixed menus in all pages

### PR DESCRIPTION
**Pull request by Anandha-Vihari**
BEFORE:
Screenshot 2024-10-16 224732

AFTER:

image

labels: ggsocext level3

### CODE REVIEW

**Comment by mansiruhil13** [comment]
issue no

**Comment by Anandha-Vihari** [comment]
https://github.com/mansiruhil13/Bobble-AI/issues/790

#790

**Comment by mansiruhil13** [comment]
there are conflicts, resolve

**Comment by Anandha-Vihari** [comment]
@mansiruhil13 

https://github.com/user-attachments/assets/66665e3e-4fb9-461d-a4d1-3ab1301997b4

**Comment by mansiruhil13** [comment]
there are some changes in footer recently. can you check your code again?

**Pull request closed without merging**
