### PR TITLE
created a basic about.html page

### PR DESCRIPTION
**Pull request by Anandha-Vihari**
about.html page is missing

so i created a about.html page and added some basic content of our project 

level 3 please 

i will add more content in about.html soon

### CODE REVIEW

**Comment by mansiruhil13** [comment]
can you share the screenshot of output?

**Comment by Anandha-Vihari** [comment]
screencapture-127-0-0-1-5500-about-html-2024-10-05-21_35_12
i know this is very basic and sick , i will modify it with a good design soon

**Comment by mansiruhil13** [comment]
ui can be far better

**Comment by Anandha-Vihari** [comment]
yeah sure i will modify it,can you please merge it now 
so,that i can change the code

**Comment by RadhikaMalpani1702** [comment]
@MastanSayyad and @sanjay-kv Can you please review this PR

**Comment by sanjay-kv** [comment]
this cant be level2 , reduce to level1 and provide access to repo so we can help you with managing labels.

@mansiruhil13

**Pull request merged**
