### PR TITLE
Fixed issues and Added new Design  

### PR DESCRIPTION
**Pull request by devanshar**
Added eye catchy designs and fixed the footer again as it was showing two 

before 
image
image

after 
image
image

### CODE REVIEW

**Comment by mansiruhil13** [comment]
no need to change for dark mode, dark mode is already assigned

**Comment by devanshar** [comment]
> no need to change for dark mode, dark mode is already assigned

not just dark but the design was changed to a eye catchy one

**Comment by devanshar** [comment]
and still it was showing two footers but in my code its just one

**Comment by mansiruhil13** [comment]
> and still it was showing two footers but in my code its just one

alright, but the issue was assigned recently

**Comment by devanshar** [comment]
> > and still it was showing two footers but in my code its just one
> 
> alright, but the issue was assigned recently

ok so should i make a new pull req for design

**Comment by mansiruhil13** [comment]
> and still it was showing two footers but in my code its just one

its' because its' not merged

**Comment by mansiruhil13** [comment]
> > > and still it was showing two footers but in my code its just one
> > 
> > 
> > alright, but the issue was assigned recently
> 
> ok so should i make a new pull req for design

no need for faq/footer now

**Comment by devanshar** [comment]
> no need for faq/footer now

ok👍

**Pull request closed without merging**
