### PR TITLE
Changes to Navbar across all pages

### LINKED ISSUE #791: [Feature Request]: I want to improve the navbar like on index.html and make it available to all other pages
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to improve the navbar on all other pages 

Screenshot (417)

Synchronize it like home page

Screenshot (418)

### Use Case

It will help improve the UI experience of users.

### Benefits

_No response_

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

### PR DESCRIPTION
**Pull request by KhawajaFashi**
## Description
fixes #791 

I have made changes to: 
- Changed the navbar across all pages
- Added navbar and dark mode in the nearby.html page
- Added chatbot and translator in the nearby.html page and other pages on which it was missing
- Some important UI changes

### CODE REVIEW

**Comment by KhawajaFashi** [comment]
There are no conflicts with the main branch you can merge it after reviewing.

Screenshot (421)

**Comment by mansiruhil13** [comment]
Screenshot 2024-10-16 234905

**Comment by KhawajaFashi** [comment]
Mam, can you please reconsider the level of this pr. Shouldn't it be level3

**Comment by KhawajaFashi** [comment]
Mam i wanted to ask if there is no issue raised for footer redesigning i would like to do it.

**Comment by mansiruhil13** [comment]
navbar changed acc to new changes. this pr don't make any blunder??

**Comment by mansiruhil13** [comment]
> Mam i wanted to ask if there is no issue raised for footer redesigning i would like to do it.

no need for footer

**Comment by KhawajaFashi** [comment]
> > Mam i wanted to ask if there is no issue raised for footer redesigning i would like to do it.
> 
> no need for footer

ok

**Comment by KhawajaFashi** [comment]
> navbar changed acc to new changes. this pr don't make any blunder??

I had tested it on my local machine it was clear if you want i can make screen recording

**Comment by mansiruhil13** [comment]
> > navbar changed acc to new changes. this pr don't make any blunder??
> 
> I had tested it on my local machine it was clear if you want i can make screen recording

yes

**Comment by KhawajaFashi** [comment]
https://drive.google.com/file/d/1GmKP5N-MwgUWok1-K983U_kNKpXIhVxO/view?usp=sharing
Recording link

**Comment by mansiruhil13** [comment]
> https://drive.google.com/file/d/1GmKP5N-MwgUWok1-K983U_kNKpXIhVxO/view?usp=sharing Recording link You can now review it mam.

request permission

**Comment by mansiruhil13** [comment]
Screenshot 2024-10-17 014503

**Comment by KhawajaFashi** [comment]
Which hover button mam can you please tell I will add it

**Pull request closed without merging**
