### PR TITLE
modification in the footer of home page

### PR DESCRIPTION
**Pull request by KunalSingh5431**
Name : modification in the footer of home page

## Description
This pull request updates the design and alignment of various components to improve the user interface and user experience. The specific changes include:

1) Updated the styling of social media icons to create a more modern and cohesive look.
2) Enhanced the design of the email input section and the submit button for better visual appeal and usability.
3) Center-aligned specific text elements to improve readability and visual balance.

## Screenshots (if applicable)
image

## Type of Change

- [ x ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

## Checklist

- [ x ] I have read the contributing document.
- [ ] I have performed a self-review of my own code.
- [ x ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have added necessary tests to ensure my changes are effective.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by mansiruhil13** [comment]
issue number??

**Comment by mansiruhil13** [comment]
and homepage footer is different from other pages.

**Comment by KunalSingh5431** [comment]
> and homepage footer is different from other pages.

no footer is same , I am just changed the search box ,submit button styles and the social media icons and align center the useful links text

**Comment by KunalSingh5431** [comment]
> issue number??

#1099

**Pull request merged**
