### PR TITLE
fix: navbar alignment issue

### PR DESCRIPTION
**Pull request by ishita-1305**
fix: #352 
how it looked before:
Screenshot 2024-10-13 144238

how it looks now after fixing the alignment issue:
Screenshot 2024-10-13 151112

### CODE REVIEW

**Comment by mansiruhil13** [comment]
there are conflicts. resolve. and there are few changes done recently, can you change into your code accordingly?

**Comment by ishita-1305** [comment]
@mansiruhil13 Okay, I’ll make the necessary changes based on the recent code updates.

**Comment by ishita-1305** [comment]
@mansiruhil13 I have committed the changes please review

https://github.com/user-attachments/assets/33a79a09-0a44-4edf-9c29-8acae53f6596

**Comment by mansiruhil13** [comment]
Screenshot 2024-10-15 191322
there are conflicts, resolve. 
and also as landing page added. you have to change in your code

**Comment by mansiruhil13** [comment]
> @mansiruhil13 i have resolved the conflicts...can u merge?

landing page was added. so there are few changes.

**Review by MastanSayyad — COMMENTED** [review]
Change with only spaces 

NO level labels!

**Comment by ishita-1305** [comment]
@MastanSayyad i committed changes in the navbar but since the landing page was added the previous design was removed...so i just made sure the branch had no conflicts...

**Pull request closed without merging**
