### PR TITLE
Added the privacy policy file on the website and improved UI. Files have been changed [privacy.html]

### PR DESCRIPTION
**Pull request by Priyank00007**
image
I have added the privacy policy file in the website and also updated the UI similar to that of "about us" page.

### CODE REVIEW

**Comment by mansiruhil13** [comment]
there are some conflicts, resolve

**Comment by mansiruhil13** [comment]
Screenshot 2024-10-08 225030

**Comment by Priyank00007** [comment]
> there are some conflicts, resolve

resolved mam

**Comment by mansiruhil13** [comment]
always mention issue no. in pr

**Comment by Priyank00007** [comment]
> always mention issue no. in pr

ok mam thanks for your time.

**Pull request merged**
