### PR TITLE
updating user css

### PR DESCRIPTION
**Pull request by Rohinipilla**
image

### CODE REVIEW

**Comment by mansiruhil13** [comment]
what changes have you created, it seems no changes has been done

**Comment by Rohinipilla** [comment]
> what changes have you created, it seems no change has been done

image
I made changes in user.html , login.html but they are already updated the UI.

**Comment by mansiruhil13** [comment]
i can't see any changes?

**Comment by Rohinipilla** [comment]
i just add hover effects to button and the div. i give the margin space between the body start and content. if this change is not good then ignore it

**Comment by Rohinipilla** [comment]
> i can't see any changes in the screenshot?

i just add hover effects to button and the div. i give the margin space between the body start and content. if this change is not good then ignore it

**Comment by mansiruhil13** [comment]
and view on map?

**Comment by mansiruhil13** [comment]
but hospital name any data? address?

**Comment by Rohinipilla** [comment]
> but hospital name any data? address?

it is given as default in the code. the maps are not given any data

**Comment by Rohinipilla** [comment]
Thank you

**Pull request merged**
