### PR TITLE
Now social media links are opening in new tab

### LINKED ISSUE #1033: [Bug]: Social Media Links Open in Same Tab, Affecting User Experience
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When clicking on the social media links, they currently open in the same tab, which negatively impacts the user experience by navigating users away from the site. I attempted to manually open the links in a new tab but realized the current implementation does not specify the target="_blank" attribute. This attribute should be added to ensure that external links open in a new tab, allowing users to stay on the site while accessing social media profiles.

### Add Screenshots

https://github.com/user-attachments/assets/3be167b7-f286-49ea-b3e6-d69f469215e2

### What browsers are you seeing the problem on?

_No response_

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

### PR DESCRIPTION
**Pull request by Ravi-1606**
---
name: Pull Request Template
about: Use this template for creating pull requests
title: '[FIX] Social media links now open in a new tab'
labels: 'bug, enhancement'
assignees: 'RaviChoudhary'

---

## Description
- This pull request addresses an issue where social media links on the site were not opening in a new tab, causing users to navigate away from the main site unintentionally.
- The bug was fixed by adding `target="_blank"` to each social media link, ensuring that they now open in a new browser tab or window. This improves user experience by allowing users to access external social media pages without leaving the main site.

- Fixes #1033 
- This pull request fixes the bug where social media links didn't open in a new tab. I resolved this by adding `target="_blank"` to each link.

## Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

- [x] I have read the contributing document.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have added necessary tests to ensure my changes are effective.
- [x] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by Ravi-1606** [comment]
@mansiruhil13 Please merge my PR. I've completed my task.

**Comment by mansiruhil13** [comment]
there are conflicts resolve. and there are few changes done, can you review you code again? please so that this pr don't make any blunder

**Comment by Ravi-1606** [comment]
I’ve reviewed the code and resolved the conflicts. However, if there are any remaining issues, please don’t hesitate to let me know. I want to ensure this PR is seamless and error-free. @mansiruhil13

**Comment by Ravi-1606** [comment]
@mansiruhil13 can you please merge this PR ?

**Pull request closed without merging**
