### PR TITLE
Improve user interaction efficiency with updates to multiple files

### PR DESCRIPTION
**Pull request by BarnaliBhowmik**
## Description
Enhanced user interaction efficiency and overall experience by updating multiple sections, including team, privacy, contact us, feedback, homepage, index, nearby, and chatbot.

## Type of Change
- [x] Documentation update
- [x] Enhancements improving user interaction efficiency
- [x] Additions primarily focused on enhancing data resources.

## Checklist
- [x] I have read the contributing document.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have added necessary tests to ensure my changes are effective.
- [x] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published in downstream modules.

## Additional Information
I reviewed your project and found it truly unique. This is my first open-source contribution, and as a newcomer, I would greatly appreciate your feedback and insights to support my learning. I'm eager to enhance my skills and contribute further to your project.

### CODE REVIEW

**Comment by BarnaliBhowmik** [comment]
@mansiruhil13 Awaiting your feedback. If the PR is beneficial to the project, please label it as 'gssoc-extd' and 'hacktoberfest-accepted'.

**Comment by mansiruhil13** [comment]
screenshot??

**Comment by BarnaliBhowmik** [comment]
Screenshot 2024-10-20 123318
Screenshot 2024-10-20 123343
Screenshot 2024-10-20 125427

**Comment by BarnaliBhowmik** [comment]
@mansiruhil13 Please share any areas where I can improve. As a newcomer, your insights would be invaluable in helping me enhance my future contributions.

**Comment by mansiruhil13** [comment]
there are conflicts. kindly resolve them and can you elaborate what changes have  you made??

**Pull request closed without merging**
