### PR TITLE
Creation of LICENSE, Contributing.md, Screenshots.md and Updated README.md file.

### PR DESCRIPTION
**Pull request by rajdeepchakraborty-rc**
## 1. Creation of **LICENSE**.
image

## 2. Updating the README.md file for better readability of the users.
- Added animated borders separating each section.
image

- Added a **Screenshots.md** file redirect in the Description section. 
image

- **Screenshots.md** contains the images previously in the **README.md** file and a link to the live demo website. This increases the cleanliness and readability of the **README.md** file.
image

## 3. Creation of Contributing.md file for Contributors.
image
image
image

- Also added a redirect to **Contributing.md** from **README.md**
image

### CODE REVIEW

**Comment by rajdeepchakraborty-rc** [comment]
Please do assign this PR to me and also make sure you assign the labels:
- level3
- gssoc-ext
- hactoberfest-accepted
Thanks for reviewing the PR.

**Comment by mansiruhil13** [comment]
in license, change ambuflow instead of name? and did you change screenshot format, change this also?

**Comment by rajdeepchakraborty-rc** [comment]
> in license, change ambuflow instead of name? and did you change screenshot format, change this also?

Sorry, can you please explain what you said? Change what?

**Comment by mansiruhil13** [comment]
change "ambuflow" that's name of project in license instead of name "anurag vishwakarma"

**Comment by mansiruhil13** [comment]
and did you change image format??? also

**Comment by rajdeepchakraborty-rc** [comment]
> change "ambuflow" that's name of project in license instead of name "anurag vishwakarma"

Yes will change that just noticed that

**Comment by rajdeepchakraborty-rc** [comment]
> and did you change image format??? also

Format of the Screenshots? If so then all I did was shift the code into a new file (Screenshots.md) and added a redirect to it in the description section(image provided above).

**Comment by rajdeepchakraborty-rc** [comment]
I have added the image for the Screenshots.md file code in the previous message.
Also here is the modified LICENSE: 
image

**Comment by rajdeepchakraborty-rc** [comment]
Please review the changes and let me know.

**Comment by mansiruhil13** [comment]
create another pr

**Comment by rajdeepchakraborty-rc** [comment]
Just a min

**Pull request closed without merging**
