### PR TITLE
Create Location

### PR DESCRIPTION
**Pull request by 23wh1a0513**

### CODE REVIEW

**Comment by 23wh1a0513** [comment]
> screenshot?? issue no??

WhatsApp Image 2024-10-09 at 10 54 04 PM

**Comment by 23wh1a0513** [comment]
Is my work merged to main

**Comment by 23wh1a0513** [comment]
> screenshot?? issue no??

@mansiruhil13 i have shared the screenshot may i know when will it be merged.

**Comment by mansiruhil13** [comment]
i am asking the screenshot of output. and separately write issue no. both are different

**Comment by 23wh1a0513** [comment]
ok

**Comment by 23wh1a0513** [comment]
> screenshot of output??

Actually i have only the code present i dont have api to integrate so i shared the code.

**Pull request closed without merging**
