### PR TITLE
Fixed hover issue in feedback page in footer section.

### PR DESCRIPTION
**Pull request by Dhruv7055**
Fixed hover issue in feedback page in footer section.
Screenshot (329)

### CODE REVIEW

**Comment by mansiruhil13** [comment]
issue no??

**Comment by Dhruv7055** [comment]
Ya i have fixed it see now

**Comment by mansiruhil13** [comment]
there is translator added and toggle key for dark theme. can you do changes into your code accordingly??

**Comment by Dhruv7055** [comment]
I have created this PR for issue #718

**Comment by Dhruv7055** [comment]
Please review my PR for issue #718 and merge it

**Comment by mansiruhil13** [comment]
is there changes acc to new one. i mean, translator and toggle key there??

**Comment by Dhruv7055** [comment]
Yes its there.

**Comment by Dhruv7055** [comment]
I have just solved hover issue in footer section of quick links and contact info, like on hovering blue color should be there as on all pages of the website.

**Pull request merged**
