### PR TITLE
[FIX] FAQ Section Added

### LINKED ISSUE #491: [Bug]: FAQ Missing
### Is there an existing issue for this?

- [X] I have searched the existing issues

## FAQ Section MISSING
https://github.com/user-attachments/assets/97ff74e0-d6bd-49fc-80fc-930ef0ca4000

### Add Screenshots

_No response_

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

### PR DESCRIPTION
**Pull request by 4F24L**
## FAQ Added

- fixes #491 

image

### CODE REVIEW

**Comment by mansiruhil13** [comment]
do changes accordingly as chatbot and some others features added recently. if i merged this, that changes have been disappeared

**Comment by 4F24L** [comment]
Okay. Making necessary changes to keep it working.

**Comment by 4F24L** [comment]
@mansiruhil13 You are doing it wrongly.

Actually, the chatbot was not there while I added this . and the PR #625 added that chatbot. and my PR is #618. You should merge #618 before #625.

You should merge PRs in ascending order. Then everything will be fine without any conflicts.

**Comment by 4F24L** [comment]
## ✅ These Are Open 
image


## ✅ You Closed These 
image

**Comment by 4F24L** [comment]
@mansiruhil13 , All resolved.

For upcoming PRs, please merge those in ascending order.

**Comment by mansiruhil13** [comment]
> @mansiruhil13 You are doing it wrongly.
> 
> Actually, the chatbot was not there while I added this . and the PR #625 added that chatbot. and my PR is #618. You should merge #618 before #625.
> 
> You should merge PRs in ascending order. Then everything will be fine without any conflicts.

but that's merged already, have to do changes accordingly

**Comment by 4F24L** [comment]
Yes, I made the required changes .

But take care when you are merging future PRs.

**Comment by 4F24L** [comment]
You can merge this PR as the chatbt will not be harmed by it.

**Pull request merged**
