### PR TITLE
Improved navigation section with SPA, icons, animation, and footer

### PR DESCRIPTION
**Pull request by Web-Dev-Learner**
### labels 

#73   , level2  , gssoc-ext   , hacktoberfest   , hacktoberfest-accepted

### changes made 

-Added navigation elements for Home, Features, Team, and Contact sections.
-Built the application as a single-page application (SPA) with smooth animations and icon integration.
-Added responsive footer with content and improved overall layout.

### screenshots 

Screenshot 2024-10-04 113300

---
Screenshot 2024-10-04 112047

Screenshot 2024-10-04 112056

Screenshot 2024-10-04 112111

Screenshot 2024-10-04 112128

Screenshot 2024-10-04 112139

### CODE REVIEW

**Comment by mansiruhil13** [comment]
amazing, but can you design logo instead ambulance monitoring system?

**Comment by Web-Dev-Learner** [comment]
> amazing, but can you design logo instead ambulance monitoring system?



Thank you , sure , I'll try my best .

**Comment by Web-Dev-Learner** [comment]
> > amazing, but can you design logo instead ambulance monitoring system?
> 
> Thank you , sure , I'll try my best .

Would you prefer a simple icon-based logo or a  image design for the Ambulance Monitoring System

**Comment by mansiruhil13** [comment]
> > > amazing, but can you design logo instead ambulance monitoring system?
> > 
> > 
> > Thank you , sure , I'll try my best .
> 
> Would you prefer a simple icon-based logo or a image design for the Ambulance Monitoring System

you can use ambulance image for logo

**Comment by mansiruhil13** [comment]
> > > > amazing, but can you design logo instead ambulance monitoring system?
> > > 
> > > 
> > > Thank you , sure , I'll try my best .
> > 
> > 
> > Would you prefer a simple icon-based logo or a image design for the Ambulance Monitoring System
> 
> you can use ambulance image for logo
for example-
373716444-ccf4c689-967d-4229-80f5-78923d2316df
but no need to write word ambuflow

**Comment by Web-Dev-Learner** [comment]
> > > > > amazing, but can you design logo instead ambulance monitoring system?
> > > > 
> > > > 
> > > > Thank you , sure , I'll try my best .
> > > 
> > > 
> > > Would you prefer a simple icon-based logo or a image design for the Ambulance Monitoring System
> > 
> > 
> > you can use ambulance image for logo
> > for example-
> > 373716444-ccf4c689-967d-4229-80f5-78923d2316df
> > but no need to write word ambuflow


ok , Thanks for your reference pic , i'll work on it.

**Comment by Web-Dev-Learner** [comment]
I added logo

### reference 
https://github.com/mansiruhil13/Bobble-AI/pull/151/

**Pull request merged**
